### ISSUE TITLE
clangd crash when hovering over an rvalue reference

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#104]
```c++
template<typename T>
T declval();

struct Test {};

int main() {
    decltype(declval<Test &&>()) t = Test();
    //                           ^  hover on t
}
```

Stacktrace:
```
#0  0x00000000005dad40 in clang::TagType::getDecl() const ()
#1  0x00000000005fd30b in clang::APValue::printPretty(llvm::raw_ostream&, clang::ASTContext const&, clang::QualType) const ()
#2  0x00000000007baba2 in clang::clangd::getHover(clang::clangd::ParsedAST&, clang::clangd::Position, clang::format::FormatStyle, clang::clangd::SymbolIndex const*) ()
#3  0x00000000006e4572 in clang::clangd::ClangdServer::findHover(llvm::StringRef, clang::clangd::Position, llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>)::{lambda(llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::Expected<clang::clangd::InputsAndAST>)#1}::operator()(llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::Expected<clang::clangd::InputsAndAST>) const [clone .isra.1105] ()
#4  0x00000000006e4c95 in void llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>::CallImpl<clang::clangd::ForwardBinder<clang::clangd::ClangdServer::findHover(llvm::StringRef, clang::clangd::Position, llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>)::{lambda(llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::Expected<clang::clangd::InputsAndAST>)#1}, llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(void*, llvm::Expected<clang::clangd::InputsAndAST>&) ()
#5  0x000000000079596c in clang::clangd::(anonymous namespace)::ASTWorker::runWithAST(llvm::StringRef, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>)::{lambda(llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>)#1}::operator()(llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>) const [clone .isra.900] ()
#6  0x0000000000796f2b in void llvm::unique_function<void ()>::CallImpl<clang::clangd::ForwardBinder<clang::clangd::(anonymous namespace)::ASTWorker::runWithAST(llvm::StringRef, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>)::{lambda(llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>)#1}, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)> > >(void*) ()
#7  0x000000000079301b in clang::clangd::(anonymous namespace)::ASTWorker::run() ()
#8  0x0000000000782791 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}>)#2}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}> > >::_M_run() ()
#9  0x000000006fd067df in libstdc++-6!atomic_flag_test_and_set_explicit () from D:\mingw64\bin\libstdc++-6.dll
#10 0x0000000064944a94 in pthread_create_wrapper () from D:\mingw64\bin\libwinpthread-1.dll
#11 0x00007ff85d47b04a in msvcrt!_beginthreadex () from C:\WINDOWS\System32\msvcrt.dll
#12 0x00007ff85d47b11c in msvcrt!_endthreadex () from C:\WINDOWS\System32\msvcrt.dll
#13 0x00007ff85c477bd4 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#14 0x00007ff85dc4ce71 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#15 0x0000000000000000 in ?? ()
```

**Comment by lh123** [comment]
Minimal repro:
```c++
struct Test {};

int main() {
    Test &&test = Test();
    //     ^^^^ hover on 'test'
}

```

**Comment by ilya-biryukov** [comment]
Thanks for the report, looking...

**Comment by ilya-biryukov** [comment]
The fix is under review: https://reviews.llvm.org/D65655

**Comment by ilya-biryukov** [comment]
Fix landed as r367687 aka https://github.com/llvm/llvm-project/commit/25082817eb6b37f3a51799b006b297c0cd742179
