### ISSUE TITLE
Multiple references to function argument

### ISSUE THREAD

**Issue by CSivira** [clangd/clangd#1369]
Clangd keeps adding more and more references to function arguments. See lines 24 & 25 below.

![image](https://user-images.githubusercontent.com/36940784/201385967-14e6bd24-59e1-4f8d-9d3c-63bd8ddf1498.png)

This is happening with every function call, or every place where this annotations are displayed.

The number of repeated annotations increases during the use of the extension, restarting VSCode solves the issue until it happens again.

**System information**

Output of `clangd --version`:
clangd version 14.0.6
Features: linux
Platform: x86_64-pc-linux-gnu

Editor/LSP plugin:
VSCode version 1.72.1 x64
Clangd extension version v0.1.23

Operating system:
Archlinux

**Comment by HighCommander4** [comment]
The fact that it happens with every function call, and that the number of repetitions is increasing, makes me suspect that clangd is crashing repeatedly. When clangd crashes, vscode restarts it, but inlay hints from the previous run may be left over.

Can you share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) please? That woudl allow us to confirm the crash theory, and if it's right then hopefully also diagnose the crash further.

**Comment by CSivira** [comment]
These are the only logs I could found about clang. Hope this helps.

```
[2022-11-15 16:49:00.598] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:49:00.598] [exthost] [error] {"_isCancelled":true,"_emitter":null}
[2022-11-15 16:51:11.656] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:51:11.657] [exthost] [error] TypeError: Cannot read properties of null (reading 'items')
	at hp.<anonymous> (/home/carlos/.vscode-oss/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.23-universal/out/bundle.js:242:10490)
	at Generator.next (<anonymous>)
	at o (/home/carlos/.vscode-oss/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.23-universal/out/bundle.js:1:1160)
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)
[2022-11-15 16:54:00.663] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:00.664] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:00.664] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:00.664] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:00.664] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:00.664] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:00.664] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:00.664] [exthost] [error] {"_isCancelled":true,"_emitter":null}
[2022-11-15 16:54:00.664] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:00.664] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:39.384] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:39.384] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:39.384] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:39.384] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:39.384] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:39.384] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
[2022-11-15 16:54:39.384] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2022-11-15 16:54:39.384] [exthost] [error] {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}
```

**Comment by HighCommander4** [comment]
@CSivira Try selecting "clangd" in the dropdown in the Output view

**Comment by CSivira** [comment]
It is a long log but searching for server o restart keyword I got this:

```
I[15:43:14.780] ASTWorker building file /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp version 2197 with command 
[/home/carlos/Code/personal/codeforces/king_scape/build]
/usr/bin/c++ --driver-mode=g++ -I/home/carlos/Code/personal/codeforces/king_scape/src -std=c++17 -o CMakeFiles/kingscape.dir/src/main.cpp.o -c -resource-dir=/usr/lib/clang/14.0.6 -- /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp
I[15:43:14.781] --> textDocument/clangd.fileStatus
I[15:43:14.781] --> textDocument/clangd.fileStatus
I[15:43:14.782] --> textDocument/clangd.fileStatus
/usr/include/c++/12.2.0/bits/basic_string.h:1292: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&]: Assertion '!empty()' failed.
/usr/lib/libLLVM-14.so(+0xcd545a)[0x7f4042ed545a]
/usr/lib/libLLVM-14.so(_ZN4llvm3sys17RunSignalHandlersEv+0x2f)[0x7f4042ed2aef]
/usr/lib/libLLVM-14.so(+0xcd2c3d)[0x7f4042ed2c3d]
/usr/lib/libc.so.6(+0x38a00)[0x7f4041c51a00]
/usr/lib/libc.so.6(+0x8864c)[0x7f4041ca164c]
/usr/lib/libc.so.6(gsignal+0x18)[0x7f4041c51958]
/usr/lib/libc.so.6(abort+0xd7)[0x7f4041c3b53d]
/usr/lib/libstdc++.so.6(+0xd2112)[0x7f4041ed2112]
/usr/bin/clangd(+0x1ea6a3)[0x5616e4af86a3]
/usr/bin/clangd(+0x1d9ad7)[0x5616e4ae7ad7]
/usr/bin/clangd(+0x1dcc7c)[0x5616e4aeac7c]
/usr/lib/libclang-cpp.so.14(+0xf7b94e)[0x7f404a37b94e]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema22CodeCompleteExpressionEPNS_5ScopeERKNS0_26CodeCompleteExpressionDataE+0x461)[0x7f404a36f8a1]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema22CodeCompleteExpressionEPNS_5ScopeENS_8QualTypeEb+0x46)[0x7f404a370186]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser19ParseCastExpressionENS0_13CastParseKindEbRbNS0_13TypeCastStateEbPb+0x596)[0x7f4049bfb1f6]
/usr/lib/libclang-cpp.so.14(+0x24c9f5d)[0x7f404b8c9f5d]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseRHSOfBinaryExpressionENS_12ActionResultIPNS_4ExprELb1EEENS_4prec5LevelE+0x1d3)[0x7f4049bf7c33]
/usr/lib/libclang-cpp.so.14(+0x24ca22d)[0x7f404b8ca22d]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser18ParseExprStatementENS0_17ParsedStmtContextE+0x50)[0x7f4049c853f0]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser42ParseStatementOrDeclarationAfterAttributesERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationERNS_25ParsedAttributesWithRangeE+0x2dc)[0x7f4049c8331c]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseStatementOrDeclarationERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationE+0xa4)[0x7f4049c83c64]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseCompoundStatementBodyEb+0x542)[0x7f4049c88a02]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser22ParseCompoundStatementEbj+0x22)[0x7f4049c88ee2]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser42ParseStatementOrDeclarationAfterAttributesERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationERNS_25ParsedAttributesWithRangeE+0x5a4)[0x7f4049c835e4]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseStatementOrDeclarationERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationE+0xa4)[0x7f4049c83c64]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser14ParseStatementEPNS_14SourceLocationENS0_17ParsedStmtContextE+0x5b)[0x7f4049c83efb]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser17ParseForStatementEPNS_14SourceLocationE+0x761)[0x7f4049c87631]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser42ParseStatementOrDeclarationAfterAttributesERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationERNS_25ParsedAttributesWithRangeE+0x5f2)[0x7f4049c83632]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseStatementOrDeclarationERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationE+0xa4)[0x7f4049c83c64]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseCompoundStatementBodyEb+0x542)[0x7f4049c88a02]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser22ParseCompoundStatementEbj+0x22)[0x7f4049c88ee2]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser42ParseStatementOrDeclarationAfterAttributesERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationERNS_25ParsedAttributesWithRangeE+0x5a4)[0x7f4049c835e4]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseStatementOrDeclarationERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationE+0xa4)[0x7f4049c83c64]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser14ParseStatementEPNS_14SourceLocationENS0_17ParsedStmtContextE+0x5b)[0x7f4049c83efb]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser19ParseWhileStatementEPNS_14SourceLocationE+0x1fd)[0x7f4049c86a4d]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser42ParseStatementOrDeclarationAfterAttributesERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationERNS_25ParsedAttributesWithRangeE+0x428)[0x7f4049c83468]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseStatementOrDeclarationERN4llvm11SmallVectorIPNS_4StmtELj32EEENS0_17ParsedStmtContextEPNS_14SourceLocationE+0xa4)[0x7f4049c83c64]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseCompoundStatementBodyEb+0x542)[0x7f4049c88a02]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseFunctionStatementBodyEPNS_4DeclERNS0_10ParseScopeE+0xda)[0x7f4049c8a4ba]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser23ParseFunctionDefinitionERNS_17ParsingDeclaratorERKNS0_18ParsedTemplateInfoEPNS0_18LateParsedAttrListE+0x44b)[0x7f4049c8b1fb]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser14ParseDeclGroupERNS_15ParsingDeclSpecENS_17DeclaratorContextEPNS_14SourceLocationEPNS0_12ForRangeInitE+0xbd9)[0x7f4049c0f0d9]
/usr/lib/libclang-cpp.so.14(+0x87a418)[0x7f4049c7a418]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser24ParseExternalDeclarationERNS_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0xa0e)[0x7f4049c8f66e]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb+0x256)[0x7f4049c8f9f6]
/usr/lib/libclang-cpp.so.14(_ZN5clang8ParseASTERNS_4SemaEbb+0x238)[0x7f4049bd9f18]
/usr/lib/libclang-cpp.so.14(_ZN5clang14FrontendAction7ExecuteEv+0x189)[0x7f404b1b3919]
/usr/bin/clangd(+0x86d813)[0x5616e517b813]
/usr/bin/clangd(+0x1ec49a)[0x5616e4afa49a]
/usr/bin/clangd(+0x1bb103)[0x5616e4ac9103]
/usr/bin/clangd(+0x1bb934)[0x5616e4ac9934]
/usr/bin/clangd(+0x326588)[0x5616e4c34588]
/usr/bin/clangd(+0x47a597)[0x5616e4d88597]
/usr/lib/libc.so.6(+0x868fd)[0x7f4041c9f8fd]
/usr/lib/libc.so.6(+0x108a60)[0x7f4041d21a60]
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
Signalled during preamble action: CodeComplete
  Filename: /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp
  Directory: /home/carlos/Code/personal/codeforces/king_scape/build
  Command Line: /usr/bin/c++ --driver-mode=g++ -I/home/carlos/Code/personal/codeforces/king_scape/src -std=c++17 -o CMakeFiles/kingscape.dir/src/main.cpp.o -c -resource-dir=/usr/lib/clang/14.0.6 -- /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp
[Info  - 3:43:15 PM] Connection to server got closed. Server will restart.
[Error - 3:43:15 PM] Request textDocument/completion failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/codeAction failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/semanticTokens/full/delta failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/codeAction failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 3:43:15 PM] Request textDocument/documentSymbol failed.
[object Object]
I[15:43:15.571] clangd version 14.0.6
I[15:43:15.571] Features: linux
I[15:43:15.571] PID: 27527
I[15:43:15.571] Working directory: /home/carlos/Code/personal/codeforces/king_scape
I[15:43:15.571] argv[0]: /usr/bin/clangd
I[15:43:15.571] Starting LSP over stdin/stdout
I[15:43:15.572] <-- initialize(0)
I[15:43:15.573] --> reply:initialize(0) 1 ms
I[15:43:15.575] <-- initialized
I[15:43:15.591] <-- textDocument/didOpen
I[15:43:15.592] Loaded compilation database from /home/carlos/Code/personal/codeforces/king_scape/build/compile_commands.json
I[15:43:15.592] ASTWorker building file /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp version 2198 with command 
[/home/carlos/Code/personal/codeforces/king_scape/build]
/usr/bin/c++ --driver-mode=g++ -I/home/carlos/Code/personal/codeforces/king_scape/src -std=c++17 -o CMakeFiles/kingscape.dir/src/main.cpp.o -c -resource-dir=/usr/lib/clang/14.0.6 -- /home/carlos/Code/personal/codeforces/king_scape/src/main.cpp
I[15:43:15.593] --> window/workDoneProgress/create(0)
I[15:43:15.593] Enqueueing 1 commands for indexing
I[15:43:15.593] --> textDocument/clangd.fileStatus
I[15:43:15.595] <-- reply(0)
I[15:43:15.595] --> $/progress
I[15:43:15.595] --> $/progress
I[15:43:15.642] <-- textDocument/completion(1)
I[15:43:15.642] <-- textDocument/documentSymbol(2)
I[15:43:15.642] <-- textDocument/codeAction(3)
I[15:43:15.643] Code complete: 0 results from Sema, 0 from Index, 0 matched, 1 from identifiers, 1 returned.
```

It says just one that the server got closed and restarted. In VSCode got this:

![image](https://user-images.githubusercontent.com/36940784/202281053-c1cd7b1e-e497-43b4-964b-1c92eeb281bd.png)

**Comment by HighCommander4** [comment]
Based on the top stack frame of the crash:

> /usr/include/c++/12.2.0/bits/basic_string.h:1292: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&]: Assertion '!empty()' failed.

I believe this is the crash that has been reported in #1216 and has recently been fixed.

The fix is available in clangd 15.0.4. (I don't see 15.0.4 on the [clangd releases](https://github.com/clangd/clangd/releases) page yet, nor am I seeing an x64 linux binary package at https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.4 (not sure why...), but you can get it from https://apt.llvm.org/, or you can get a weekly clangd snapshot like [this one](https://github.com/clangd/clangd/releases/tag/snapshot_20221113)).

**Comment by CSivira** [comment]
Thanks for the response. I'll try that in the future because arch doesn't have that version yet. For now its enough to know this will do.
