### ISSUE TITLE
clangd runs out of my memory

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#152]
* clangd version: `clangd version 10.0.0 (https://github.com/llvm/llvm-project.git dd507867efdc04a9d117cfe10bd291aa4b44ebbb)`
* gcc version: `gcc version 8.2.0 (Rev3, Built by MSYS2 project)`
* OS: `windows10`
```c++
#include <iostream>

int main() {
    std::cout << "hello" << std::endk; // std::endk cause this problem in my computer
}
```
clangd run out of my memory when I wrote this code.
![1](https://user-images.githubusercontent.com/10697249/64842395-b6800f00-d634-11e9-8303-be3913fb4fe3.png)
Clangd stays in the "parsing includes" state.
![2](https://user-images.githubusercontent.com/10697249/64842397-b8e26900-d634-11e9-9d78-8185f5702cbb.png)

backtrace:
```
#0  0x0000000000cfabfc in clang::Sema::AddMethodCandidate(clang::CXXMethodDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, llvm::MutableArrayRef<clang::ImplicitConversionSequence>) ()
#1  0x0000000000cfbb06 in clang::Sema::AddMethodCandidate(clang::DeclAccessPair, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) ()
#2  0x0000000000cfbcf1 in clang::Sema::AddMemberOperatorCandidates(clang::OverloadedOperatorKind, clang::SourceLocation, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, clang::SourceRange) ()
#3  0x0000000000d0cd03 in clang::Sema::CreateOverloadedBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::UnresolvedSetImpl const&, clang::Expr*, clang::Expr*, bool) ()
#4  0x0000000000bd9fbc in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) ()
#5  0x0000000000bd9a01 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) ()
#6  0x0000000000bd9a01 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) ()
#7  0x0000000000bc9247 in (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) ()
#8  0x0000000000bc9cf2 in clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) ()
#9  0x0000000000bcab9c in clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) ()
#10 0x0000000000d1fdf9 in clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) ()
#11 0x00000000017acf1b in clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) ()
#12 0x00000000017adeea in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#13 0x00000000017aef50 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#14 0x00000000017b3c5e in clang::Parser::ParseCompoundStatementBody(bool) ()
#15 0x00000000017b68d0 in clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) ()
#16 0x0000000001725fe0 in clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) ()
#17 0x000000000174384d in clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) ()
#18 0x0000000001720a1a in clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) ()
#19 0x0000000001721323 in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.282] ()
#20 0x0000000001727dbb in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#21 0x0000000001728a9c in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) ()
#22 0x000000000171ccec in clang::ParseAST(clang::Sema&, bool, bool) ()
#23 0x00000000008c1219 in clang::FrontendAction::Execute() ()
#24 0x000000000075ed3d in clang::clangd::ParsedAST::build(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, clang::clangd::SymbolIndex const*, clang::clangd::ParseOptions const&) ()
#25 0x0000000000761558 in clang::clangd::buildAST(llvm::StringRef, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, clang::clangd::ParseInputs const&, std::shared_ptr<clang::clangd::PreambleData const>) ()
#26 0x00000000007b5f82 in clang::clangd::(anonymous namespace)::ASTWorker::update(clang::clangd::ParseInputs, clang::clangd::WantDiagnostics)::{lambda()#1}::operator()() ()
#27 0x00000000007b0d29 in clang::clangd::(anonymous namespace)::ASTWorker::run() ()
#28 0x00000000007a0071 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}>)#2}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}> > >::_M_run() ()
#29 0x000000006fd067df in libstdc++-6!atomic_flag_test_and_set_explicit () from D:\clangd\bin\libstdc++-6.dll
#30 0x0000000064944b80 in ?? () from E:\Development\msys64\mingw64\bin\libwinpthread-1.dll
#31 0x00007ffe6cf8b04a in msvcrt!_beginthreadex () from C:\WINDOWS\System32\msvcrt.dll
#32 0x00007ffe6cf8b11c in msvcrt!_endthreadex () from C:\WINDOWS\System32\msvcrt.dll
#33 0x00007ffe6c427bd4 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#34 0x00007ffe6d7ecee1 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#35 0x0000000000000000 in ?? ()
```

**Comment by hokein** [comment]
Thanks for the report and the testcase. I can reproduce the issue on Linux as well.

**Comment by hokein** [comment]
bisect told that the https://reviews.llvm.org/D62648 is the culprit.

**Comment by hokein** [comment]
Should be fixed in upstream r371859.
