### ISSUE TITLE
Cannot run compiler-rt tests with llvm-lit directly

### ISSUE THREAD

**Issue by wzssyqa** [clangd/clangd#1738]
```
$ ./bin/llvm-lit ../compiler-rt/test/asan/TestCases/Linux/printf-fortify-2.c 
llvm-lit: /home/syq/git-push/llvm-project/llvm/utils/lit/lit/TestingConfig.py:151: fatal: unable to parse config file '/home/syq/git-push/llvm-project/compiler-rt/test/asan/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/home/syq/git-push/llvm-project/llvm/utils/lit/lit/TestingConfig.py", line 139, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/home/syq/git-push/llvm-project/compiler-rt/test/asan/lit.cfg.py", line 22, in <module>
    config.name = "AddressSanitizer" + config.name_suffix
AttributeError: 'TestingConfig' object has no attribute 'name_suffix'
```

**Comment by zyn0217** [comment]
compiler-rt is maintained by llvm and doesn't concern clangd. Could you please submit the issue to [llvm-project/issues](https://github.com/llvm/llvm-project/issues)?

**Comment by wzssyqa** [comment]
Sorry for noisy...

**Comment by wzssyqa** [comment]
Sorry for the noise
