### ISSUE TITLE
segfault while indexing

### ISSUE THREAD

**Issue by yshui** [clangd/clangd#1871]
**Logs**

```
I[17:14:37.826] Indexed ../wine/libs/zydis/src/SharedData.c (12 symbols, 247071 refs, 24 files)
 #0 0x00007f2633442503 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM-16.so+0xe1f503)
 #1 0x00007f263343f7bf llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-16.so+0xe1c7bf)
 #2 0x00007f263343f90d (/usr/lib/libLLVM-16.so+0xe1c90d)
 #3 0x00007f26320f2710 (/usr/lib/libc.so.6+0x3e710)
 #4 0x00007f263b3c7f24 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/usr/lib/libclang-cpp.so.16+0x9c3f24)
 #5 0x00007f263b3c8a84 clang::ASTContext::getTypeInfo(clang::Type const*) const (/usr/lib/libclang-cpp.so.16+0x9c4a84)
 #6 0x00007f263b3c8c2b clang::ASTContext::getTypeInfoInChars(clang::Type const*) const (/usr/lib/libclang-cpp.so.16+0x9c4c2b)
 #7 0x00007f263b3c8dcb clang::ASTContext::getTypeSizeInChars(clang::QualType) const (/usr/lib/libclang-cpp.so.16+0x9c4dcb)
 #8 0x00007f263bbda04c clang::Sema::ActOnFields(clang::Scope*, clang::SourceLocation, clang::Decl*, llvm::ArrayRef<clang::Decl*>, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&) (/usr/lib/libclang-cpp.so.16+0x11d604c)
 #9 0x00007f263b30b105 clang::Parser::ParseStructUnionBody(clang::SourceLocation, clang::TypeSpecifierType, clang::RecordDecl*) (/usr/lib/libclang-cpp.so.16+0x907105)
#10 0x00007f263b35363f clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/usr/lib/libclang-cpp.so.16+0x94f63f)
#11 0x00007f263b302f1f clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/usr/lib/libclang-cpp.so.16+0x8fef1f)
#12 0x00007f263b3b1612 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/lib/libclang-cpp.so.16+0x9ad612)
#13 0x00007f263b3b1fc9 (/usr/lib/libclang-cpp.so.16+0x9adfc9)
#14 0x00007f263b3bccd6 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/lib/libclang-cpp.so.16+0x9b8cd6)
#15 0x00007f263b3bd073 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/lib/libclang-cpp.so.16+0x9b9073)
#16 0x00007f263b2f0f49 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.16+0x8ecf49)
#17 0x00007f263cb227c9 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.16+0x211e7c9)
#18 0x0000560aa338844e (/usr/bin/clangd+0x8ae44e)
#19 0x0000560aa3366496 (/usr/bin/clangd+0x88c496)
#20 0x0000560aa33df6c9 (/usr/bin/clangd+0x9056c9)
#21 0x00007f26321409eb (/usr/lib/libc.so.6+0x8c9eb)
#22 0x00007f26321c47cc (/usr/lib/libc.so.6+0x1107cc)
```

stack trace from gdb has a bit more detail:

```
#0  0x00007fdc5d596f24 in clang::Expr::getDependence ()
    at /usr/src/debug/clang/clang-16.0.6.src/include/clang/AST/Expr.h:157
#1  clang::Expr::isInstantiationDependent () at /usr/src/debug/clang/clang-16.0.6.src/include/clang/AST/Expr.h:216
#2  clang::DecltypeType::isSugared () at /usr/src/debug/clang/clang-16.0.6.src/lib/AST/Type.cpp:3533
#3  clang::DecltypeType::desugar () at /usr/src/debug/clang/clang-16.0.6.src/lib/AST/Type.cpp:3536
#4  clang::ASTContext::getTypeInfoImpl ()
    at /usr/src/debug/clang/clang-16.0.6.src/build/include/clang/AST/TypeNodes.inc:35
#5  0x00007fdc5d597a84 in clang::ASTContext::getTypeInfo ()
    at /usr/src/debug/clang/clang-16.0.6.src/lib/AST/ASTContext.cpp:1945
#6  0x00007fdc5d597c2b in clang::ASTContext::getTypeInfoInChars ()
```

**System information**

clangd version 16.0.6
Features: linux
Platform: x86_64-pc-linux-gnu

Editor/LSP plugin: vscode

Operating system: Linux

**Comment by HighCommander4** [comment]
The first thing I would suggest is checking whether the crash still occurs with the latest snapshot build from trunk: https://github.com/clangd/clangd/releases/tag/snapshot_20231217

If it does, a code example triggering the crash would be helpful for further investigation.

**Comment by yshui** [comment]
I am on `clangd version 18.0.0 (/srcdest/llvm-project ef250fc47bd655cf9f110339ebc4851ba95957f6)` and the segfault is gone.

Should I close this?

**Comment by HighCommander4** [comment]
Thanks for checking!

Yeah, let's close this. There won't be any more 17.x releases so there's no point tracking down what specifically fixed the crash.
