### ISSUE TITLE
Repeated crashing

### ISSUE THREAD

**Issue by dwilliamson** [clangd/clangd#222]
Issue Type: <b>Bug</b>

The clangd server is crashing constantly, after about 20 minutes of use, forcing a restart of VSCode.

Here is the output:

```
I[12:02:18.251] <-- textDocument/codeAction(4)
I[12:02:18.252] --> textDocument/clangd.fileStatus
I[12:02:18.252] Updating file c:\dev\Celtoys\Star\src\CppClient\TinyCRT\VC\vc.cpp with command 
[c:\dev\Celtoys\Star]
c:\program files\llvm\bin\clang-tool -xc++ -m32 -std=c++14 -DCLCPP_SIZE_TYPE=size_t -DCLCPP_SIZE_TYPE_HEX_FORMAT="lX" -DVSCODE_INTELLISENSE -DRMT_USE_TINYCRT -DWITH_WASAPI -Isrc\CppClient -Iextern\bullet\src -Iextern\clReflect\release\inc -Iextern\DynamicPatcher\Source -Iextern\soloud\include -Iextern -Ibuild\gen\Debug -Isrc\CppClient\TinyCRT\stdlib c:\dev\Celtoys\Star\src\CppClient\TinyCRT\VC\vc.cpp -fsyntax-only -resource-dir=c:\program files\llvm\lib\clang\9.0.0
 #0 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x162e2d0 c:\program files\llvm\bin\clangd.exe 0x162ff9a
 #1 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1630112 c:\program files\llvm\bin\clangd.exe 0x1635ee2
 #2 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x13b1988 c:\program files\llvm\bin\clangd.exe 0x13b3799
 #3 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x137c396 c:\program files\llvm\bin\clangd.exe 0x137b01c
 #4 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1383e69 c:\program files\llvm\bin\clangd.exe 0x1384b06
 #5 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1308cee c:\program files\llvm\bin\clangd.exe 0x134b9b2
 #6 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x130806b c:\program files\llvm\bin\clangd.exe 0x13078aa
 #7 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1306893 c:\program files\llvm\bin\clangd.exe 0x132801e
 #8 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1308049 c:\program files\llvm\bin\clangd.exe 0x13079fc
 #9 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1306893 c:\program files\llvm\bin\clangd.exe 0x1304dd2
#10 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1300bfe c:\program files\llvm\bin\clangd.exe 0x4ec742
#11 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x3359bd c:\program files\llvm\bin\clangd.exe 0x339cdd
#12 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x397f3f c:\program files\llvm\bin\clangd.exe 0x3953a1
#13 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x422a91 c:\program files\llvm\bin\clangd.exe 0x422c89
#14 0x00007ff69fa9e2d0 (c:\program files\llvm\bin\clangd.exe+0x162e2d0)
#15 0x00007ff69fa9ff9a (c:\program files\llvm\bin\clangd.exe+0x162ff9a)
#16 0x00007ff69faa0112 (c:\program files\llvm\bin\clangd.exe+0x1630112)
0x00007FF69FA9E2D0 (0x0000000000000000 0x0000000000000000 0x0000026E12AD0000 0x00007FFBDEA9922B)
0x00007FF69FA9FF9A (0x0000026E1549EEA0 0x00007FFBDEA940DA 0x0000026E12AD0000 0x0000026E12AD0000)
0x00007FF69FAA0112 (0x0000026E15F1CF10 0x0000000000000004 0x0000026E15F1CF10 0x0000000000000004)
0x00007FF69FAA5EE2 (0x0000026E00000000 0x00007FF69F8BE934 0x000000000028190D 0x00007FF69E9ED4FB)
0x00007FF69F821988 (0x0000026E156AC068 0x0000026E156ABFD0 0x0000026E156ABF88 0x0000026E156AB300)
0x00007FF69F823799 (0x0000026E151AA8B8 0x00007FF69FA3B38F 0x0000000000000000 0x0000000000000000)
0x00007FF69F7EC396 (0x0000000000000000 0x0000026E15311408 0x000098C2505B1369 0x0000026E153110B0)
0x00007FF69F7EB01C (0x000000A2F970BF30 0x0000000800000000 0x0000000000000010 0x000000A2F970BFE0)
0x00007FF69F7F3E69 (0x0000026E15C2F098 0x00007FF69EFD06CC 0x0000000000000000 0x0000026E151EED80)
0x00007FF69F7F4B06 (0x000000A200000001 0x0000000000000000 0x0000000000000000 0x0000026E15C2EE10)
0x00007FF69F778CEE (0x0000026E156ABF88 0x0000026E156AB300 0x0000026E156AC020 0x0000000000000000)
0x00007FF69F7BB9B2 (0x0000026E151AA882 0x00007FF69FA45BFC 0x0000000000000000 0x0000000000000000)
0x00007FF69F77806B (0x0000026E0000039F 0x0000026E158016C0 0x0000026E145609C0 0x0000026E1473AAD0)
0x00007FF69F7778AA (0x000000000000039F 0x0000026E15C2EF38 0x0000000000000398 0x00007FF69E597D3B)
0x00007FF69F776893 (0x0000000000000002 0x0000026E15C2EE10 0x0000003010288202 0x0000026E151B1F30)
0x00007FF69F79801E (0x0000026E151AA5D4 0x00007FF69FA33E08 0x000098C2505B7B29 0x0000026E151AA880)
0x00007FF69F778049 (0x0000026E1540FCA0 0x00007FF69FA3B3B0 0x0000026E151AA87D 0x000000A2F970D7D0)
0x00007FF69F7779FC (0x000098C2505B79D9 0x0000026E15C29F68 0x0000000000000000 0x0000026E14B75450)
0x00007FF69F776893 (0x000000A2F970DAE8 0x0000000000000000 0x0000026E153110A0 0x000000A2F970DAD8)
0x00007FF69F774DD2 (0x0000000000000000 0x0000026E15C126C0 0x000000A2F970DE70 0x00007FF69E974882)
0x00007FF69F770BFE (0x0000026E154D8F90 0x00007FF69F04C5E2 0x0000026E1460C0D0 0x0000026E1460C0D0)
0x00007FF69E95C742 (0x000000A2F970E330 0x000000A2F970E0E0 0x0000000000000000 0x0000000000000000)
0x00007FF69E7A59BD (0x0000026E147A9500 0x00007FF69E758CC0 0x1FFFFFFFFFFFFFFF 0x000000A2F970F130)
0x00007FF69E7A9CDD (0x000000A2F970F201 0x0000000000000420 0x000000A2F970F2E8 0x0000026E147139C0)
0x00007FF69E807F3F (0x0000026E1454BFE0 0xFFFFFFFFFFFFFFFF 0x0000026E1454BFE0 0x000000A2F970F670)
0x00007FF69E8053A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF69E892A91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF69E892C89 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFBDB57E3FE (0x0000000000000000 0x0000[Error - 12:02:18] Connection to server got closed. Server will not be restarted.
[Error - 12:02:18] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:902:25)
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2236:42)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\main.js:154:15)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2223:18)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:238:26)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 12:02:18] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:902:25)
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2236:42)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\main.js:154:15)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2223:18)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:238:26)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 12:02:18] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:902:25)
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2236:42)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\main.js:154:15)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2223:18)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:238:26)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 12:02:18] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:902:25)
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2236:42)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\main.js:154:15)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2223:18)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:238:26)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

Extension version: 0.0.19
Clangd version: 9.0.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (25.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dwilliamson** [comment]
I've reduced the file that it's crashing on to this:

```cpp
void fn()
{
    __asm
    {
        cmp     cl,64
    }
}
```

It doesn't crash if there are no assembly instructions in there. This is MSVC-specific notation but note the use of `-m32` in the command-line. This used to work on older versions.

**Comment by dwilliamson** [comment]
Clang 9.0.0 itself works fine: https://godbolt.org/z/5mYzTm

**Comment by dwilliamson** [comment]
Retiring this as it's not a vscode-clangd bug. If I ever get round to sending an email to the bugzilla admins for permission to send them bugs then I'll report it there. For now, I'm just defining these out for intellisense.

**Comment by sam-mccall** [comment]
This is the right place for clangd bugs of any kind. We've moved out of the LLVM bugzilla partly because of the account issue you mention :-)

Thanks for the minimized test case. The stack trace isn't symbolized but from the logs I'm 90% sure this is a code action prepare() or possibly Selection tree.
(And probably not windows-specific, which is convenient)

**Comment by sam-mccall** [comment]
Back at my desk... indeed this reproduces on linux but it looks like a parser crash (in background-index, see frame 25) rather than a code-action issue.

```
I[09:20:32.503] Updating file /usr/local/google/home/sammccall/temp/test.cc with command 
[/usr/local/google/home/sammccall/temp/]
/usr/lib/llvm-8/bin/clang++ --driver-mode=g++ -xc++ -m32 -std=c++14 -fms-extensions test.cc -fsyntax-only -resource-dir=/usr/local/google/home/sammccall/llvmbuild-mono/lib/clang/10.0.0
 #0 0x00000000004c3d54 PrintStackTrace /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/Support/Unix/Signals.inc:548:13
 #1 0x00000000004c3d54 PrintStackTraceSignalHandler(void*) /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/Support/Unix/Signals.inc:608:0
 #2 0x00000000004c1acc llvm::sys::RunSignalHandlers() /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/Support/Signals.cpp:69:18
 #3 0x00000000004c3f5c SignalHandler(int) /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/Support/Unix/Signals.inc:380:3
 #4 0x00007fdfeaaea3a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x123a0)
 #5 0x00000000012d47a9 startswith /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/StringRef.h:277:21
 #6 0x00000000012d47a9 llvm::AsmLexer::AsmLexer(llvm::MCAsmInfo const&) /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/MC/MCParser/AsmLexer.cpp:34:0
 #7 0x00000000012ac31d AsmParser /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/MC/MCParser/AsmParser.cpp:703:7
 #8 0x00000000012ac31d llvm::createMCAsmParser(llvm::SourceMgr&, llvm::MCContext&, llvm::MCStreamer&, llvm::MCAsmInfo const&, unsigned int) /usr/local/google/home/sammccall/src/llvm-mono/llvm/lib/MC/MCParser/AsmParser.cpp:6072:0
 #9 0x000000000129dc60 clang::Parser::ParseMicrosoftAsmStatement(clang::SourceLocation) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseStmtAsm.cpp:606:7
#10 0x0000000001293355 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseStmt.cpp:293:11
#11 0x0000000001291e2b clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseStmt.cpp:106:20
#12 0x0000000001299e81 clang::Parser::ParseCompoundStatementBody(bool) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseStmt.cpp:1079:11
#13 0x000000000129ad10 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseStmt.cpp:2164:21
#14 0x00000000011fce47 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:0:0
#15 0x00000000012174a7 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseDecl.cpp:2066:16
#16 0x00000000011fbf52 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:1095:10
#17 0x00000000011fb995 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:1111:12
#18 0x00000000011faa79 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:931:12
#19 0x00000000011f8866 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:682:10
#20 0x00000000011f81c7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/Parser.cpp:560:26
#21 0x00000000011f3e13 clang::ParseAST(clang::Sema&, bool, bool) /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Parse/ParseAST.cpp:157:25
#22 0x000000000105f800 clang::FrontendAction::Execute() /usr/local/google/home/sammccall/src/llvm-mono/clang/lib/Frontend/FrontendAction.cpp:940:10
#23 0x0000000000ac49cb getPtr /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/Support/Error.h:273:42
#24 0x0000000000ac49cb operator bool /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/Support/Error.h:236:0
#25 0x0000000000ac49cb clang::clangd::BackgroundIndex::index(clang::tooling::CompileCommand) /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/index/Background.cpp:410:0
#26 0x0000000000ac87bc _M_data /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:176:28
#27 0x0000000000ac87bc _M_is_local /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:211:0
#28 0x0000000000ac87bc _M_dispose /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:220:0
#29 0x0000000000ac87bc ~basic_string /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:657:0
#30 0x0000000000ac87bc ~CompileCommand /usr/local/google/home/sammccall/src/llvm-mono/clang/include/clang/Tooling/CompilationDatabase.h:44:0
#31 0x0000000000ac87bc operator() /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/index/Background.cpp:199:0
#32 0x0000000000ac87bc std::_Function_handler<void (), clang::clangd::BackgroundIndex::indexFileTask(clang::tooling::CompileCommand)::$_3>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:297:0
#33 0x0000000000aceb40 getValue /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/Optional.h:73:5
#34 0x0000000000aceb40 getPointer /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/Optional.h:254:0
#35 0x0000000000aceb40 operator-> /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/Optional.h:261:0
#36 0x0000000000aceb40 clang::clangd::BackgroundQueue::work(std::function<void ()>) /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/index/BackgroundQueue.cpp:41:0
#37 0x0000000000ac7130 ~_Function_base /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:256:11
#38 0x0000000000ac7130 operator() /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/index/Background.cpp:154:0
#39 0x0000000000ac7130 void llvm::unique_function<void ()>::CallImpl<clang::clangd::BackgroundIndex::BackgroundIndex(clang::clangd::Context, clang::clangd::FileSystemProvider const&, clang::clangd::GlobalCompilationDatabase const&, llvm::unique_function<clang::clangd::BackgroundIndexStorage* (llvm::StringRef)>, unsigned long)::$_1>(void*) /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/FunctionExtras.h:157:0
#40 0x0000000000aa4e08 PointerIntPair /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/PointerIntPair.h:48:12
#41 0x0000000000aa4e08 unique_function /usr/local/google/home/sammccall/src/llvm-mono/llvm/include/llvm/ADT/FunctionExtras.h:174:0
#42 0x0000000000aa4e08 operator() /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/Threading.cpp:93:0
#43 0x0000000000aa4e08 __invoke_impl<void, (lambda at /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/Threading.cpp:88:7), std::__cxx11::basic_string<char>, llvm::unique_function<void ()>, llvm::detail::scope_exit<(lambda at /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/Threading.cpp:77:44)> > /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:60:0
#44 0x0000000000aa4e08 __invoke<(lambda at /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/Threading.cpp:88:7), std::__cxx11::basic_string<char>, llvm::unique_function<void ()>, llvm::detail::scope_exit<(lambda at /usr/local/google/home/sammccall/src/llvm-mono/clang-tools-extra/clangd/Threading.cpp:77:44)> > /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95:0
#45 0x0000000000aa4e08 _M_invoke<0, 1, 2, 3> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:244:0
#46 0x0000000000aa4e08 operator() /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:253:0
#47 0x0000000000aa4e08 std::thread::_State_impl<std::thread::_Invoker<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::$_4, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::$_0> > > >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:196:0
#48 0x00007fdfeaddfb2f (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbbb2f)
#49 0x00007fdfeaadfc73 start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7c73)
#50 0x00007fdfe9e4ddef clone (/lib/x86_64-linux-gnu/libc.so.6+0xf8def)
```

**Comment by sam-mccall** [comment]
So I think what's happening is:
 - MS asm syntax doesn't put its asm in strings
 - clang lexes the tokens and then wants to parse the asm
 - the actual parse depends on the target machine
 - we don't link in (all of) backend, so the backend MCAsmInfo is null
 - there's some code that checks for the backend not being available, but it doesn't check this condition exactly

**Comment by dwilliamson** [comment]
Crikey, top job!
