### ISSUE TITLE
clangd crash when hovering.

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#235]
+ clangd:
```
clangd version 10.0.0 (https://github.com/llvm/llvm-project.git de21704ba96fa80d3e9402f12c6505917a3885f4)
```
```c++
template<typename T>
struct Test {
    void test();
};

int main() {
    Test<int>().test();
    //          ^^^^ hover on test
}
```

```
#0  0x0000000000aa7bb0 in clang::clangd::(anonymous namespace)::getDeclForComment(clang::NamedDecl const*) ()
#1  0x0000000000aae2ba in clang::clangd::(anonymous namespace)::getHoverContents(clang::Decl const*, clang::clangd::SymbolIndex const*) ()
#2  0x0000000000ab2937 in clang::clangd::getHover(clang::clangd::ParsedAST&, clang::clangd::Position, clang::format::FormatStyle, clang::clangd::SymbolIndex const*) ()
#3  0x0000000000a21e42 in clang::clangd::ClangdServer::findHover(llvm::StringRef, clang::clangd::Position, llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>)::{lambda(llvm::Expected<clang::clangd::InputsAndAST>)#1}::operator()(llvm::Expected<clang::clangd::InputsAndAST>) ()
#4  0x0000000000a2247d in void llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>::CallImpl<clang::clangd::ClangdServer::findHover(llvm::StringRef, clang::clangd::Position, llvm::unique_function<void (llvm::Expected<llvm::Optional<clang::clangd::HoverInfo> >)>)::{lambda(llvm::Expected<clang::clangd::InputsAndAST>)#1}>(void*, llvm::Expected<clang::clangd::InputsAndAST>&) ()
#5  0x0000000000b3c892 in clang::clangd::(anonymous namespace)::ASTWorker::runWithAST(llvm::StringRef, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>)::{lambda()#1}::operator()() ()
#6  0x0000000000b37d75 in clang::clangd::(anonymous namespace)::ASTWorker::run() ()
#7  0x0000000000b26ec1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}>)#2}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}> > >::_M_run() ()
#8  0x00007fc10f788ee4 in std::execute_native_thread_routine (__p=0x3e9a3d0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#9  0x00007fc10fcf14cf in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007fc10f48f2d3 in clone () from /usr/lib/libc.so.6
```

**Comment by lh123** [comment]
@kadircet Maybe caused by D71596

**Comment by kadircet** [comment]
fixed by https://github.com/llvm/llvm-project/commit/14e11005d1a6ac1fecb230c470e9011d6956b8e4
