### ISSUE TITLE
Clangd crashed

### ISSUE THREAD

**Issue by hyd-dev** [clangd/clangd#361]
Clangd crashed when opening a file (`utility.hpp`) of my project.

File content:
[file_content.zip](https://github.com/clangd/clangd/files/4567676/file_content.zip)

`dmesg` shows:
`segfault at 1c ip 000055cedc6a991f sp 00007ff9cbb13d50 error 4 in clangd[55cedc526000+6ef000]`

Backtrace:
```
#0  0x000055aacf3ec91f in clang::clangd::(anonymous namespace)::TargetFinder::add(clang::Decl const*, clang::clangd::DeclRelationSet) ()
#1  0x000055aacf3ec874 in clang::TypeVisitor<clang::clangd::(anonymous namespace)::TargetFinder::add(clang::QualType, clang::clangd::DeclRelationSet)::Visitor, void>::Visit(clang::Type const*) [clone .constprop.0] ()
#2  0x000055aacf3ed3db in clang::clangd::allTargetDecls(clang::ast_type_traits::DynTypedNode const&) ()
#3  0x000055aacf3ed76e in clang::clangd::explicitReferenceTargets(clang::ast_type_traits::DynTypedNode, clang::clangd::DeclRelationSet) ()
#4  0x000055aacf3ede65 in clang::TypeLocVisitor<clang::clangd::(anonymous namespace)::refInTypeLoc(clang::TypeLoc)::Visitor, void>::Visit(clang::UnqualTypeLoc) ()
#5  0x000055aacf3edb31 in clang::TypeLocVisitor<clang::clangd::(anonymous namespace)::refInTypeLoc(clang::TypeLoc)::Visitor, void>::Visit(clang::UnqualTypeLoc) ()
#6  0x000055aacf3ef204 in clang::clangd::(anonymous namespace)::ExplicitReferenceCollector::visitNode(clang::ast_type_traits::DynTypedNode) ()
#7  0x000055aacf3f57ab in clang::clangd::(anonymous namespace)::ExplicitReferenceCollector::TraverseElaboratedTypeLoc(clang::ElaboratedTypeLoc) ()
#8  0x000055aacf3ffe7a in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseCXXUnresolvedConstructExpr(clang::CXXUnresolvedConstructExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#9  0x000055aacf3fcff9 in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#10 0x000055aacf3fd74d in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseFunctionProtoTypeLoc(clang::FunctionProtoTypeLoc) ()
#11 0x000055aacf3fea4f in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseFunctionHelper(clang::FunctionDecl*) ()
#12 0x000055aacf3f12a2 in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseDecl(clang::Decl*) [clone .part.0] ()
#13 0x000055aacf4033c2 in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseFunctionTemplateDecl(clang::FunctionTemplateDecl*) ()
#14 0x000055aacf3f2830 in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseDeclContextHelper(clang::DeclContext*) [clone .part.0] ()
#15 0x000055aacf3f0f1b in clang::RecursiveASTVisitor<clang::clangd::(anonymous namespace)::ExplicitReferenceCollector>::TraverseDecl(clang::Decl*) [clone .part.0] ()
#16 0x000055aacf3f2747 in clang::clangd::findExplicitReferences(clang::ASTContext const&, llvm::function_ref<void (clang::clangd::ReferenceLoc)>) ()
#17 0x000055aacf465f4d in clang::clangd::getSemanticHighlightings(clang::clangd::ParsedAST&) ()
#18 0x000055aacf3a20f5 in clang::clangd::(anonymous namespace)::UpdateIndexCallbacks::onMainAST(llvm::StringRef, clang::clangd::ParsedAST&, llvm::function_ref<void (llvm::function_ref<void ()>)>) ()
#19 0x000055aacf498a0a in clang::clangd::(anonymous namespace)::ASTWorker::update(clang::clangd::ParseInputs, clang::clangd::WantDiagnostics)::{lambda()#1}::operator()()
    ()
#20 0x000055aacf4930eb in clang::clangd::(anonymous namespace)::ASTWorker::run() ()
#21 0x000055aacf486e1e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}>)#2}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void ()>, clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::{lambda()#1}> > >::_M_run() ()
#22 0x00007fb776539a94 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#23 0x00007fb77e1df432 in start_thread () from /lib64/libpthread.so.0
#24 0x00007fb7762359d3 in clone () from /lib64/libc.so.6
```

**System information**
Output of `clangd --version`: clangd version 10.0.0 (Fedora 10.0.0-1.fc32)
Editor/LSP plugin: VSCodium `llvm-vs-code-extensions.vscode-clangd`
Operating system: Fedora 32

**Comment by hokein** [comment]
I didn't reproduce it with a head-version clangd, we landed a few patches that fix semantic highlighting crashes recently, I believe they also fix this one, please retry with a newer version https://github.com/clangd/clangd/releases.
