### ISSUE TITLE
Crash when opening file in VSCode

### ISSUE THREAD

**Issue by RedDwarf69** [clangd/clangd#378]
Opening impl/to_array.hpp from [clangd_bug2.tar.gz](https://github.com/clangd/clangd/files/4601909/clangd_bug2.tar.gz) crashes clangd 10.0.0, running on VSCode from Fedora 32.

```
I[23:12:43.353] clangd version 10.0.0 (Fedora 10.0.0-2.fc32)
I[23:12:43.353] PID: 43854
I[23:12:43.353] Working directory: /home/reddwarf/git/dock/clangd
I[23:12:43.353] argv[0]: clangd
I[23:12:43.353] argv[1]: --log=verbose
I[23:12:43.353] Starting LSP over stdin/stdout
V[23:12:43.353] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true,"isPreferredSupport":true},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"preselectSupport":true,"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"selectionRange":{"dynamicRegistration":true},"semanticHighlightingCapabilities":{"semanticHighlighting":true},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"failureHandling":"textOnlyTransactional","resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"vscode","version":"1.44.2"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"processId":43819,"rootPath":"/home/reddwarf/git/dock/clangd","rootUri":"file:///home/reddwarf/git/dock/clangd","trace":"off","workspaceFolders":[{"name":"clangd","uri":"file:///home/reddwarf/git/dock/clangd"}]}}

I[23:12:43.353] <-- initialize(0)
I[23:12:43.354] --> reply:initialize(0) 0 ms
V[23:12:43.354] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",">",":"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticHighlighting":{"scopes":[["variable.other.cpp"],["variable.other.local.cpp"],["variable.parameter.cpp"],["entity.name.function.cpp"],["entity.name.function.method.cpp"],["entity.name.function.method.static.cpp"],["variable.other.field.cpp"],["variable.other.field.static.cpp"],["entity.name.type.class.cpp"],["entity.name.type.enum.cpp"],["variable.other.enummember.cpp"],["entity.name.type.typedef.cpp"],["entity.name.type.dependent.cpp"],["entity.name.other.dependent.cpp"],["entity.name.namespace.cpp"],["entity.name.type.template.cpp"],["storage.type.primitive.cpp"],["entity.name.function.preprocessor.cpp"],["meta.disabled"]]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":2,"typeHierarchyProvider":true,"workspaceSymbolProvider":true}}}

V[23:12:43.383] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[23:12:43.383] <-- initialized
I[23:12:43.383] unhandled notification initialized
V[23:12:43.384] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#pragma once\n\n#include <to_array.hpp>\n\n#include <detail/to_array.hpp>\n\ntemplate<class T, std::size_t N>\nconstexpr auto to_array(T (&array)[N]) -> std::array<std::remove_cv_t<T>, N>\n{\n    return detail::to_array_impl(array, std::make_index_sequence<N>{});\n}\n","uri":"file:///home/reddwarf/git/dock/clangd/include/impl/to_array.hpp","version":1}}}

I[23:12:43.384] <-- textDocument/didOpen
I[23:12:43.384] Enqueueing 1 commands for indexing
I[23:12:43.385] --> textDocument/clangd.fileStatus
V[23:12:43.385] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes","uri":"file:///home/reddwarf/git/dock/clangd/include/impl/to_array.hpp"}}

I[23:12:43.385] Updating file /home/reddwarf/git/dock/clangd/include/impl/to_array.hpp with command inferred from /home/reddwarf/git/dock/clangd/main.cpp
[/home/reddwarf/git/dock/clangd/build]
/usr/bin/clang++-10 --driver-mode=g++ -I../include -g -c -std=gnu++17 /home/reddwarf/git/dock/clangd/include/impl/to_array.hpp -fsyntax-only -resource-dir=/usr/lib64/clang/10.0.0
V[23:12:43.386] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name to_array.hpp -mrelocation-model static -mthread-model posix -mframe-pointer=all -fmath-errno -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -fno-split-dwarf-inlining -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -resource-dir /usr/lib64/clang/10.0.0 -I ../include -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/x86_64-redhat-linux -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib64/clang/10.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=gnu++17 -fdeprecated-macro -fdebug-compilation-dir /home/reddwarf/git/dock/clangd/build -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -faddrsig -x c++-header /home/reddwarf/git/dock/clangd/include/impl/to_array.hpp
V[23:12:43.386] Building first preamble for /home/reddwarf/git/dock/clangd/include/impl/to_array.hpp
V[23:12:43.392] BackgroundIndex: building version 1 after loading index from disk
V[23:12:43.418] BackgroundIndex: serving version 1 (2309622 bytes)
V[23:12:43.444] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///home/reddwarf/git/dock/clangd/include/impl/to_array.hpp"}}}

I[23:12:43.444] <-- textDocument/documentSymbol(1)
V[23:12:43.445] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/reddwarf/git/dock/clangd/include/impl/to_array.hpp"}}}

I[23:12:43.445] <-- textDocument/documentLink(2)
V[23:12:43.602] index AST for ../include/impl/to_array.hpp (main=false): 
  symbol slab: 2292 symbols, 650656 bytes
  ref slab: 0 symbols, 0 refs, 136 bytes
  relations slab: 216 relations, 4376 bytes
V[23:12:43.641] Built preamble of size 1002876 for file /home/reddwarf/git/dock/clangd/include/impl/to_array.hpp
V[23:12:43.644] index AST for /home/reddwarf/git/dock/clangd/build/../include/impl/to_array.hpp (main=true): 
  symbol slab: 1 symbols, 4456 bytes
  ref slab: 4 symbols, 4 refs, 4328 bytes
  relations slab: 0 relations, 24 bytes
 #0 0x00007f19ab6986ee llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib64/libLLVM-10.so+0xa416ee)
 #1 0x00007f19ab6969c4 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-10.so+0xa3f9c4)
 #2 0x00007f19ab696b56 (/lib64/libLLVM-10.so+0xa3fb56)
 #3 0x00007f19b27f0a90 __restore_rt (/lib64/libpthread.so.0+0x14a90)
 #4 0x0000558ee364694f ../include/clang/AST/DeclBase.h:432:51
 #5 0x0000558ee364694f clang::NamedDecl::classof(clang::Decl const*) ../include/clang/AST/Decl.h:437:58
 #6 0x0000558ee364694f llvm::isa_impl<clang::NamedDecl, clang::Decl, void>::doit(clang::Decl const&) /usr/include/llvm/Support/Casting.h:58:23
 #7 0x0000558ee364694f llvm::isa_impl_cl<clang::NamedDecl, clang::Decl const*>::doit(clang::Decl const*) /usr/include/llvm/Support/Casting.h:106:36
 #8 0x0000558ee364694f llvm::isa_impl_wrap<clang::NamedDecl, clang::Decl const*, clang::Decl const*>::doit(clang::Decl const* const&) /usr/include/llvm/Support/Casting.h:132:40
 #9 0x0000558ee364694f llvm::isa_impl_wrap<clang::NamedDecl, clang::Decl const* const, clang::Decl const*>::doit(clang::Decl const* const&) /usr/include/llvm/Support/Casting.h:123:60
#10 0x0000558ee364694f bool llvm::isa<clang::NamedDecl, clang::Decl const*>(clang::Decl const* const&) /usr/include/llvm/Support/Casting.h:143:74
#11 0x0000558ee364694f llvm::cast_retty<clang::NamedDecl, clang::Decl const*>::ret_type llvm::dyn_cast<clang::NamedDecl, clang::Decl const>(clang::Decl const*) /usr/include/llvm/Support/Casting.h:343:16
#12 0x0000558ee364694f add ../tools/extra/clangd/FindTarget.cpp:232:51
#13 0x0000558ee36468a4 ../tools/extra/clangd/FindTarget.cpp:410:11
#14 0x0000558ee36468a4 Visit include/clang/AST/TypeNodes.inc:65:1
#15 0x0000558ee36468a4 ../tools/extra/clangd/FindTarget.cpp:410:11
#16 0x0000558ee36468a4 Visit include/clang/AST/TypeNodes.inc:65:1
#17 0x0000558ee364740b add ../tools/extra/clangd/FindTarget.cpp:442:32
#18 0x0000558ee364740b clang::clangd::allTargetDecls(clang::ast_type_traits::DynTypedNode const&) ../tools/extra/clangd/FindTarget.cpp:501:15
#19 0x0000558ee364779e /usr/include/llvm/ADT/SmallVector.h:52:32
#20 0x0000558ee364779e llvm::SmallVectorTemplateCommon<std::pair<clang::NamedDecl const*, clang::clangd::DeclRelationSet>, void>::end() /usr/include/llvm/ADT/SmallVector.h:129:41
#21 0x0000558ee364779e clang::clangd::explicitReferenceTargets(clang::ast_type_traits::DynTypedNode, clang::clangd::DeclRelationSet) ../tools/extra/clangd/FindTarget.cpp:532:18
#22 0x0000558ee3647e95 clang::clangd::ReferenceLoc::operator=(clang::clangd::ReferenceLoc&&) ../tools/extra/clangd/FindTarget.h:119:8
#23 0x0000558ee3647e95 llvm::optional_detail::OptionalStorage<clang::clangd::ReferenceLoc, false>::operator=(clang::clangd::ReferenceLoc&&) /usr/include/llvm/ADT/Optional.h:104:13
#24 0x0000558ee3647e95 llvm::Optional<clang::clangd::ReferenceLoc>::operator=(clang::clangd::ReferenceLoc&&) /usr/include/llvm/ADT/Optional.h:231:13
#25 0x0000558ee3647e95 ../tools/extra/clangd/FindTarget.cpp:683:56
#26 0x0000558ee3647e95 Visit include/clang/AST/TypeNodes.inc:65:1
#27 0x0000558ee3647b61 ../tools/extra/clangd/FindTarget.cpp:651:7
#28 0x0000558ee3647b61 Visit include/clang/AST/TypeNodes.inc:42:1
#29 0x0000558ee3649234 refInTypeLoc ../tools/extra/clangd/FindTarget.cpp:716:3
#30 0x0000558ee3649234 explicitReference ../tools/extra/clangd/FindTarget.cpp:828:30
#31 0x0000558ee3649234 visitNode ../tools/extra/clangd/FindTarget.cpp:844:45
#32 0x0000558ee364f7db ../tools/extra/clangd/FindTarget.cpp:733:12
#33 0x0000558ee364f7db ../include/clang/AST/RecursiveASTVisitor.h:465:72
#34 0x0000558ee364f7db include/clang/AST/TypeNodes.inc:42:1
#35 0x0000558ee364f7db ../include/clang/AST/RecursiveASTVisitor.h:1337:1
#36 0x0000558ee364f7db ../tools/extra/clangd/FindTarget.cpp:741:58
#37 0x0000558ee3659eaa ../include/clang/AST/RecursiveASTVisitor.h:2531:1
#38 0x0000558ee3657029 /usr/include/llvm/ADT/SmallVector.h:127:45
#39 0x0000558ee3657029 end /usr/include/llvm/ADT/SmallVector.h:129:32
#40 0x0000558ee3657029 ../include/clang/AST/RecursiveASTVisitor.h:663:19
#41 0x0000558ee364b2d2 ../include/clang/AST/RecursiveASTVisitor.h:2077:1
#42 0x0000558ee364b2d2 include/clang/AST/DeclNodes.inc:401:1
#43 0x0000558ee365d3f2 ../include/clang/AST/RecursiveASTVisitor.h:1788:1
#44 0x0000558ee364c777 ../include/clang/AST/RecursiveASTVisitor.h:184:7
#45 0x0000558ee364c777 clang::clangd::findExplicitReferences(clang::ASTContext const&, llvm::function_ref<void (clang::clangd::ReferenceLoc)>) ../tools/extra/clangd/FindTarget.cpp:879:46
#46 0x0000558ee36bff4d clang::clangd::getSemanticHighlightings(clang::clangd::ParsedAST&) ../tools/extra/clangd/SemanticHighlighting.cpp:351:46
#47 0x0000558ee35fc125 std::_Vector_base<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::_Vector_impl_data::_M_copy_data(std::_Vector_base<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::_Vector_impl_data const&) /usr/include/c++/10/bits/stl_vector.h:111:13
#48 0x0000558ee35fc125 std::_Vector_base<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::_Vector_impl_data::_M_swap_data(std::_Vector_base<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::_Vector_impl_data&) /usr/include/c++/10/bits/stl_vector.h:123:16
#49 0x0000558ee35fc125 std::vector<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::_M_move_assign(std::vector<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >&&, std::integral_constant<bool, true>) /usr/include/c++/10/bits/stl_vector.h:1818:28
#50 0x0000558ee35fc125 std::vector<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >::operator=(std::vector<clang::clangd::HighlightingToken, std::allocator<clang::clangd::HighlightingToken> >&&) /usr/include/c++/10/bits/stl_vector.h:714:16
#51 0x0000558ee35fc125 onMainAST ../tools/extra/clangd/ClangdServer.cpp:78:51
#52 0x0000558ee36f29ea ../tools/extra/clangd/TUScheduler.cpp:375:40
#53 0x0000558ee36ed0cb run ../tools/extra/clangd/TUScheduler.cpp:708:34
#54 0x0000558ee36e0dfe llvm::PointerIntPair<llvm::PointerUnion<llvm::unique_function<void ()>::TrivialCallback*, llvm::unique_function<void ()>::NonTrivialCallbacks*>, 1u, bool, llvm::PointerLikeTypeTraits<llvm::PointerUnion<llvm::unique_function<void ()>::TrivialCallback*, llvm::unique_function<void ()>::NonTrivialCallbacks*> >, llvm::PointerIntPairInfo<llvm::PointerUnion<llvm::unique_function<void ()>::TrivialCallback*, llvm::unique_function<void ()>::NonTrivialCallbacks*>, 1u, llvm::PointerLikeTypeTraits<llvm::PointerUnion<llvm::unique_function<void ()>::TrivialCallback*, llvm::unique_function<void ()>::NonTrivialCallbacks*> > > >::getPointer() const /usr/include/llvm/ADT/PointerIntPair.h:59:58
#55 0x0000558ee36e0dfe llvm::unique_function<void ()>::~unique_function() /usr/include/llvm/ADT/FunctionExtras.h:177:42
#56 0x0000558ee36e0dfe llvm::unique_function<void ()>::operator=(llvm::unique_function<void ()>&&) /usr/include/llvm/ADT/FunctionExtras.h:228:27
#57 0x0000558ee36e0dfe llvm::unique_function<void ()>::operator=(llvm::unique_function<void ()>&&) /usr/include/llvm/ADT/FunctionExtras.h:221:20
#58 0x0000558ee36e0dfe ../tools/extra/clangd/Threading.cpp:93:18
#59 0x0000558ee36e0dfe __invoke_impl<void, clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda(std::string, llvm::unique_function<void()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> >)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::unique_function<void()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > > /usr/include/c++/10/bits/invoke.h:60:36
#60 0x0000558ee36e0dfe __invoke<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda(std::string, llvm::unique_function<void()>, llvm::detail::scope_exit<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_fun[Info  - 23:12:44] Connection to server got closed. Server will restart.
[Error - 23:12:44] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 23:12:44] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/reddwarf/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
```

**Comment by kadircet** [comment]
This was fixed with https://github.com/llvm/llvm-project/commit/9a5c448a31bacc08e73fcae4636094f9b6e2be6a. Unfortunately it didn't make into the clangd-10 release. So you need to either build from head or use a nightly build from https://github.com/clangd/clangd/releases.
