### ISSUE TITLE
c++ clangd crash

### ISSUE THREAD

**Issue by apmanol** [clangd/clangd#531]
Hello,

`clangd` server crashes in parsing some file.

**Logs**
From IDE
```
Traceback (most recent call last):
  File "/projects/Thirdparty/ycmd/third_party/bottle/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/projects/Thirdparty/ycmd/third_party/bottle/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/projects/Thirdparty/ycmd/ycmd/watchdog_plugin.py", line 97, in wrapper
    return callback( *args, **kwargs )
  File "/projects/Thirdparty/ycmd/ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/projects/Thirdparty/ycmd/ycmd/handlers.py", line 122, in GetCompletions
    completions = filetype_completer.ComputeCandidates( request_data )
  File "/projects/Thirdparty/ycmd/ycmd/completers/cpp/clangd_completer.py", line 335, in ComputeCandidates
    return super().ComputeCandidates( request_data )
  File "/projects/Thirdparty/ycmd/ycmd/completers/completer.py", line 286, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/projects/Thirdparty/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1281, in _GetCandidatesFromSubclass
    codepoint )
  File "/projects/Thirdparty/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1247, in ComputeCandidatesInner
    REQUEST_TIMEOUT_COMPLETION )
  File "/projects/Thirdparty/ycmd/ycmd/completers/language_server/language_server_completer.py", line 437, in GetResponse
    response = self.GetResponseAsync( request_id, message )
  File "/projects/Thirdparty/ycmd/ycmd/completers/language_server/language_server_completer.py", line 430, in GetResponseAsync
    self.WriteData( message )
  File "/projects/Thirdparty/ycmd/ycmd/completers/language_server/language_server_completer.py", line 725, in WriteData
    self._server_stdin.write( data )
ValueError: write to closed file
```

Stack trace:
```
[08:55:30.916] Code complete: sema context MacroNameUse, query scopes [] (AnyScope=true), expected type <none>
 #0 0x000000000053e0da llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x53e0da)
 #1 0x000000000053be1c llvm::sys::RunSignalHandlers() (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x53be1c)
 #2 0x000000000053bf83 SignalHandler(int) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x53bf83)
 #3 0x00007f469c35cb20 __restore_rt (/lib64/libpthread.so.0+0x14b20)
 #4 0x00000000006e9f50 clang::RawComment::RawComment(clang::SourceManager const&, clang::SourceRange, clang::CommentOptions const&, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x6e9f50)
 #5 0x00000000012caf76 clang::Sema::ActOnComment(clang::SourceRange) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x12caf76)
 #6 0x00000000010bcf30 (anonymous namespace)::ActionCommentHandler::HandleComment(clang::Preprocessor&, clang::SourceRange) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x10bcf30)
 #7 0x00000000008faca7 clang::Preprocessor::HandleComment(clang::Token&, clang::SourceRange) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8faca7)
 #8 0x00000000008ad127 clang::Lexer::SkipBlockComment(clang::Token&, char const*, bool&) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8ad127)
 #9 0x00000000008b1ee6 clang::Lexer::LexTokenInternal(clang::Token&, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8b1ee6)
#10 0x00000000008f9cbf clang::Preprocessor::Lex(clang::Token&) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8f9cbf)
#11 0x00000000008c0294 clang::Preprocessor::CheckEndOfDirective(char const*, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8c0294)
#12 0x00000000008c0956 clang::Preprocessor::SkipExcludedConditionalBlock(clang::SourceLocation, clang::SourceLocation, bool, bool, clang::SourceLocation) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8c0956)
#13 0x00000000008cae21 clang::Preprocessor::HandleIfdefDirective(clang::Token&, clang::Token const&, bool, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8cae21)
#14 0x00000000008cc176 clang::Preprocessor::HandleDirective(clang::Token&) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8cc176)
#15 0x00000000008b2208 clang::Lexer::LexTokenInternal(clang::Token&, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8b2208)
#16 0x00000000008f9cbf clang::Preprocessor::Lex(clang::Token&) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x8f9cbf)
#17 0x00000000010bccbb clang::ParseAST(clang::Sema&, bool, bool) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x10bccbb)
#18 0x0000000000f3cb31 clang::FrontendAction::Execute() (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0xf3cb31)
#19 0x00000000009a3252 clang::clangd::(anonymous namespace)::semaCodeComplete(std::unique_ptr<clang::CodeCompleteConsumer, std::default_delete<clang::CodeCompleteConsumer> >, clang::CodeCompleteOptions const&, clang::clangd::(anonymous namespace)::SemaCompleteInput const&, clang::clangd::IncludeStructure*) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x9a3252)
#20 0x00000000009af38e clang::clangd::codeComplete(llvm::StringRef, clang::tooling::CompileCommand const&, clang::clangd::PreambleData const*, llvm::StringRef, clang::clangd::Position, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, clang::clangd::CodeCompleteOptions, clang::clangd::SpeculativeFuzzyFind*) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x9af38e)
#21 0x0000000000991d73 clang::clangd::ClangdServer::codeComplete(llvm::StringRef, clang::clangd::Position, clang::clangd::CodeCompleteOptions const&, llvm::unique_function<void (llvm::Expected<clang::clangd::CodeCompleteResult>)>)::'lambda'(llvm::Expected<clang::clangd::InputsAndPreamble>)::operator()(llvm::Expected<clang::clangd::InputsAndPreamble>) (/projects/Thirdparty/ycmd/third_party/clangd/output/bin/clangd+0x991d73)

```

**System information**
Output of `clangd --version`:
```clangd/output/bin/clangd --version 
clangd version 10.0.0 (https://github.com/ycm-core/llvm 038587147cf2f97d1c3e677042f69560c65b5bea)
```
Editor/LSP plugin: emacs/ycmd-core
Operating system: fedora 31

**Comment by kadircet** [comment]
I beleive this has been fixed in the meantime, could you try with release candidate 2 from https://prereleases.llvm.org/11.0.0/ ?

If the crash is still happening we'll need the code for the file you are working on (possibly a minimized version) to repro.

**Comment by apmanol** [comment]
Ok, I will try to provide either the input file or try the clang 11

**Comment by hokein** [comment]
the crash stack looks like similar to #332

**Comment by apmanol** [comment]
> Ok, I will try to provide either the input file or try the clang 11

You know how it is, when you add debug symbols and increase the log severity the crash doesn't appear :-)

**Comment by kadircet** [comment]
so are you saying that you were able to reproduce with clangd-11 in release configuration but cannot repro with a debug binary?

or have you just built a clangd from head and it doesn't repro ?

**Comment by apmanol** [comment]
> so are you saying that you were able to reproduce with clangd-11 in release configuration but cannot repro with a debug binary?
> 
> or have you just built a clangd from head and it doesn't repro ?

Sorry for the confusing message :-)
Rebuild with debug symbol  and increased the log severity but I can't reproduce the problem, so as to provide the input file the produces the problem.

No luck with the clangd-11 so far.
