### ISSUE TITLE
Weird crash on function call hover for function with default args

### ISSUE THREAD

**Issue by gkarlos** [clangd/clangd#551]
Not sure if this is an issue of the extesnion or clangd itself, but I have the following code:
```cpp
  IRBuilder<> IRB(InsertBefore);
  if ( GlobalVariableForSymbol.find(symbol) == GlobalVariableForSymbol.end()) {
    GlobalVariableForSymbol[symbol] = IRB.CreateGlobalStringPtr(symbol);
  }
```
And the signature of `CreateGlobalStringPtr` is:
```cpp
  Constant *CreateGlobalStringPtr(StringRef Str, const Twine &Name = "", unsigned AddressSpace = 0) { ... }
```

When i hover over the call to `CreateGlobalStringPtr` its working fine. Now if i provide a second or third argument (or both), e.g `IRB.CreateGlobalStringPtr(symbol, "globalStr")`, and then i hover over the call again, clangd crashes.
It works fine for other functions i tried, but somehow crashes for this one.

**Logs**
```
[Error - 12:58:40 PM] Request textDocument/hover failed.
  Message: Task was cancelled.
  Code: -32001 
V[12:58:40.949] <<< {
  "id": 6,
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "position": {
      "character": 52,
      "line": 355
    },
    "textDocument": {
      "uri": "file:///home/gkarlos/Projects/kerma/lib/Transforms/Instrumentation.cpp"
    }
  }
}

I[12:58:40.949] <-- textDocument/hover(6)
[Error - 12:58:41 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:58:41 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/connection.js:1009:27)
	at Object.dispose (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-languageclient/lib/common/client.js:71:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-languageclient/lib/common/client.js:2312:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-languageclient/lib/node/main.js:146:15)
	at closeHandler (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-languageclient/lib/common/client.js:2299:18)
	at CallbackList.invoke (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/events.js:54:39)
	at Emitter.fire (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/events.js:116:36)
	at closeHandler (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/connection.js:255:26)
	at CallbackList.invoke (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/events.js:54:39)
	at Emitter.fire (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/events.js:116:36)
	at StreamMessageWriter.fireClose (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:41:27)
	at Socket.<anonymous> (/home/gkarlos/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.7/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:74:42)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
```

**System information**
Clangd version (from the log, or `clangd --version`): 10.0.0
clangd extension version: 0.17
Operating system: xubuntu 18.04 LTS

**Comment by HighCommander4** [comment]
Moved to clangd repo as this is a server crash.

A couple of questions:

  * If you run clangd with `--log=verbose` (bya dding this to `clangd.arguments` in the vscode settings), do you get additional output that includes a backtrace for the crash?
  * Are you able to share a complete code file that triggers the crash?

**Comment by hokein** [comment]
Note that you're using clangd 10, we have plenty fixes after that, so this crash is likely fixed in trunk. I'd suggest you trying the upcoming release: https://prereleases.llvm.org/11.0.0/.

**Comment by gkarlos** [comment]
> Moved to clangd repo as this is a server crash.

Thanks!

> * If you run clangd with `--log=verbose` (by adding this to `clangd.arguments` in the vscode settings), do you get additional output that includes a backtrace for the crash?

I think this output is with `--log=verbose` already. I can check again later to confirm.

> * Are you able to share a complete code file that triggers the crash?

If you are looking for an MWE that wouldn't help though anyway as there are multiple dependencies. Would the function that contains the triggering line help? Otherwise i can try craft an MWE that triggers the error.

> Note that you're using clangd 10, we have plenty fixes after that, so this crash is likely fixed in trunk. I'd suggest you trying the upcoming release: https://prereleases.llvm.org/11.0.0/.

Thanks, i'll try it.
