### ISSUE TITLE
Cannot run clangd tests with llvm-lit directly

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#66]
Run this:
```bash
$LLVM/bin/llvm-lit -vv $LLVM/clang-tools-extra/clangd/test/rename.test
```
Expected: the test is run.
Actual: an error is produced
```
llvm-lit: /home/ibiryukov/projects/llvm/llvm/utils/lit/lit/TestingConfig.py:102: fatal: unable to parse config file '/home/ibiryukov/projects/llvm/clang-tools-extra/clangd/test/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/home/ibiryukov/projects/llvm/llvm/utils/lit/lit/TestingConfig.py", line 89, in load_from_path                                                                                            
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/home/ibiryukov/projects/llvm/clang-tools-extra/clangd/test/lit.cfg.py", line 4, in <module>                                                                                              
    lit.llvm.llvm_config.use_clang()
  File "/home/ibiryukov/projects/llvm/llvm/utils/lit/lit/llvm/config.py", line 413, in use_clang                                                                                                  
    self.add_tool_substitutions(tool_substitutions)
  File "/home/ibiryukov/projects/llvm/llvm/utils/lit/lit/llvm/config.py", line 272, in add_tool_substitutions                                                                                     
    search_dirs = [self.config.llvm_tools_dir]
AttributeError: TestingConfig instance has no attribute 'llvm_tools_dir'
```

**Comment by ilya-biryukov** [comment]
@sam-mccall could you take a look please? There's probably something missing in our configuration, but I have no clue how lit works...

**Comment by hokein** [comment]
I think it is fixed in https://github.com/llvm/llvm-project/commit/cb74d2e1bdec8510f4ddd41e1ec879d745f40597 by @kadircet.
