### ISSUE TITLE
Crash when Navigating into #import

### ISSUE THREAD

**Issue by cpsauer** [clangd/clangd#660]
Please describe the problem.

I'm seeing a reproducible crash right after I CMD+click into a system framework (e.g. #import <UIKit/UIKit.h>) (from Obj-C++ on macOS). VSCode navigates into the file and then a message appears stating that the clangd has crashed repeatedly and won't be restarted. 

I'm not sure which exactly which details matter to the crash, but I know it's not just for UIKit; it's occurred on every system framework I've tried. C++ headers, like the standard library and third-party libraries, don't lead to the same crash, and everything else in clangd is working. 

Further, it's building the file for the framework header that seems to cause the crash, not the CMD+click itself. Restarting the language server with the header still open leads to an immediate crash in the same way.

**Logs**
Unfortunately, the logs didn't show me that much. But the snippet around the issue looks like the following. There are 4 instances of that last error, followed by several attempts at a clangd restart, each of which fails the same way, immediately after trying to process UIKit.
```
I[21:51:14.990] --> textDocument/clangd.fileStatus
I[21:51:15.116] <-- textDocument/definition(55)
I[21:51:15.116] --> reply:textDocument/definition(55) 0 ms
I[21:51:15.116] --> textDocument/clangd.fileStatus
I[21:51:15.260] <-- textDocument/didOpen
I[21:51:15.260] <-- textDocument/documentLink(56)
I[21:51:15.260] <-- textDocument/codeAction(57)
I[21:51:15.261] <-- textDocument/documentSymbol(58)
I[21:51:15.261] <-- textDocument/semanticTokens/full(59)
I[21:51:15.286] ASTWorker building file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h version 1 with command inferred from external/GoogleToolboxForMac/pod_support/Headers/Private/GoogleToolboxForMac-prefix.pch
[/private/var/tmp/_bazel_cpsauer/79f6da2a1111e791e2fbf4f2d7fbef1b/execroot/__main__]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -D_FORTIFY_SOURCE=1 -fstack-protector -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -DNS_BLOCK_ASSERTIONS=1 -include external/GoogleToolboxForMac/pod_support/Headers/Private/GoogleToolboxForMac-prefix.pch -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -iquote external/GoogleToolboxForMac -iquote bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-2c7291cd6708/bin/external/GoogleToolboxForMac -Iexternal/GoogleToolboxForMac/pod_support/Headers/Public -Ibazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-2c7291cd6708/bin/external/GoogleToolboxForMac/GoogleToolboxForMac_module_map -DOS_IOS -fno-autolink -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -fno-objc-arc -miphoneos-version-min=9.0 -fno-aligned-allocation -Ibazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-2c7291cd6708/bin/external/GoogleToolboxForMac/ -fobjc-weak -Wnon-modular-include-in-framework-module -g -stdlib=libc++ -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -fdiagnostics-show-note-include-stack -fno-common -fembed-bitcode-marker -fmessage-length=0 -fpascal-strings -fstrict-aliasing -Wno-error=nonportable-include-path -DPOD_CONFIGURATION_RELEASE=1 -DNS_BLOCK_ASSERTIONS=1 -Iexternal/GoogleToolboxForMac/pod_support/Headers/Public/GoogleToolboxForMac/ -fmodule-name=GoogleToolboxForMac -fmodules -Os -DNDEBUG=1 -Wno-unused-variable -Winit-self -Wno-extra -c /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h -fsyntax-only -resource-dir=/Users/cpsauer/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
I[21:51:15.288] --> textDocument/clangd.fileStatus
[Info  - 9:51:15 PM] Connection to server got closed. Server will restart.
[Error - 9:51:15 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at ClangdLanguageClient.handleConnectionClosed (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at ClangdLanguageClient.handleConnectionClosed (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/Users/cpsauer/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:51:15 PM] Request textDocument/codeAction failed.
...same trace...
[Error - 9:51:15 PM] Request textDocument/documentSymbol failed.
...same trace...
[Error - 9:51:15 PM] Request textDocument/semanticTokens/full failed.
...etc.
```

**System information**
Output of `clangd --version`: 11
Editor/LSP plugin: VSCode
Operating system: macOS 11

**Comment by cpsauer** [comment]
After several days of the issue, it has mysteriously gone away. No idea what change caused the fix.
