### ISSUE TITLE
clangd crash on .mm file when indexing with "-fmodules" flag 

### ISSUE THREAD

**Issue by drink-crow** [clangd/clangd#677]
I use clangd for cmake project which mixed C/C++ and Objective-C/C++ because Apple Metal kit only have OC/Swift entry. 

when I just add `add_compile_options(-fmodules -fcxx-modules)` in my CMakeLists.txt, project build but clangd crash
after sevral hours hard work,
I found that replace `add_compile_options(-fmodules -fcxx-modules)` with 
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fmodules")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcxx-modules")
```
clangd works, but can not phase a header file what have `@import something`, but i can easy solve it by change it to `#import something.h` because of only Objective-C object I used just MetalKit

I check the `compile_commands.json` and found that if a .mm file have command "-fmodules" would lead to Clangd crash

Clangd have no problem with my other CMake project which have no Objective-C content

Can somebody tell what is wrong, Thank you very much.

**Logs**
```
I[14:16:00.280] clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
I[14:16:00.280] PID: 20402
I[14:16:00.280] Working directory: /Users/rdacs/Desktop/Project/qtMetal
I[14:16:00.280] argv[0]: /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd
I[14:16:00.280] argv[1]: --compile-commands-dir=/Users/rdacs/Desktop/Project/qtMetal/build
I[14:16:00.280] argv[2]: --completion-style=detailed
I[14:16:00.280] argv[3]: --query-driver=/usr/bin/clang++
I[14:16:00.280] argv[4]: --log=verbose
V[14:16:00.280] User config file is /Users/rdacs/Library/Preferences/clangd/config.yaml
I[14:16:00.280] Starting LSP over stdin/stdout
V[14:16:00.281] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticHighlightingCapabilities":{"semanticHighlighting":true},"semanticTokens":{"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.52.1"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"en-us","processId":17617,"rootPath":"/Users/rdacs/Desktop/Project/qtMetal","rootUri":"file:///Users/rdacs/Desktop/Project/qtMetal","trace":"off","workspaceFolders":[{"name":"qtMetal","uri":"file:///Users/rdacs/Desktop/Project/qtMetal"}]}}

I[14:16:00.281] <-- initialize(0)
I[14:16:00.281] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
V[14:16:00.281] Invoking /usr/bin/xcrun to find clang installation
V[14:16:00.289] Invoking /usr/bin/xcrun to find clang installation
I[14:16:00.297] --> reply:initialize(0) 16 ms
V[14:16:00.297] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","member","function","member","variable","class","enum","enumConstant","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)"}}}

V[14:16:00.299] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[14:16:00.299] <-- initialized
V[14:16:00.299] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"objective-cpp","text":"#include \"AAPLRenderer.h\"\n#include <QtGui>\n\nint main(int argc, char **argv)\n{\n    // This example demonstrates how to integrate Metal rendering\n    // with Qt by controlling a Metal view using a QWindow. The Metal\n    // part of the example is copied from the hellotriangle example.\n\n    QGuiApplication app(argc, argv);\n    QWindow *window = nullptr;\n    AAPLRenderer *renderer = nil;\n\n    // Create UI after event loop has started.\n    QTimer::singleShot(0, [&window, &renderer]() {\n\n        // Create Metal view and default device\n        MTKView *view = [[[MTKView alloc] init] autorelease];\n        view.device = MTLCreateSystemDefaultDevice();\n        if (!view.device)\n            qFatal(\"Metal is not supported\");\n\n        // Load shaders from Qt resources\n        QFile shadersFile(\":/hellotriangleshaders.metallib\");\n        shadersFile.open(QIODevice::ReadOnly);\n        QByteArray shaders = shadersFile.readAll();\n        dispatch_data_t data = dispatch_data_create(shaders.constData(), shaders.size(),\n                               dispatch_get_main_queue(), DISPATCH_DATA_DESTRUCTOR_DEFAULT);\n        NSError *error = nil;\n        id <MTLLibrary> library = [view.device newLibraryWithData:data error:&error];\n        dispatch_release(data);\n        if (error)\n            qWarning() << \"Shader Error\" << error;\n\n        // Create Renderer\n        renderer = [[AAPLRenderer alloc] initWithMetalKitView:view library:library];\n        [renderer mtkView:view drawableSizeWillChange:view.drawableSize];\n        view.delegate = renderer;\n\n        // Create and show a Qt Window which controls the metal view\n        window = QWindow::fromWinId((WId)view);\n        window->setTitle(\"QWindow with MTKView\");\n        window->resize(640, 480);\n        window->show();\n    });\n\n    // Start the event loop\n    int code = app.exec();\n\n    // Clean up on exit. The QWindow will release the MTKView on destruction.\n    delete window;\n    [renderer release];\n\n    return code;\n}","uri":"file:///Users/rdacs/Desktop/Project/qtMetal/main.mm","version":1}}}

I[14:16:00.299] <-- textDocument/didOpen
I[14:16:00.300] Loaded compilation database from /Users/rdacs/Desktop/Project/qtMetal/build
I[14:16:00.300] --> window/workDoneProgress/create(0)
V[14:16:00.300] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}

I[14:16:00.300] Enqueueing 5 commands for indexing
V[14:16:00.300] <<< {"id":0,"jsonrpc":"2.0","result":null}

I[14:16:00.300] <-- reply(0)
I[14:16:00.300] --> $/progress
V[14:16:00.300] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}

I[14:16:00.300] --> $/progress
V[14:16:00.300] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}

V[14:16:00.306] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/rdacs/Desktop/Project/qtMetal/main.mm"}}}

I[14:16:00.306] <-- textDocument/documentSymbol(1)
V[14:16:00.306] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":7,"line":44},"start":{"character":7,"line":44}},"textDocument":{"uri":"file:///Users/rdacs/Desktop/Project/qtMetal/main.mm"}}}

I[14:16:00.306] <-- textDocument/codeAction(2)
V[14:16:00.306] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///Users/rdacs/Desktop/Project/qtMetal/main.mm"}}}

I[14:16:00.306] <-- textDocument/documentLink(3)
V[14:16:00.326] System include extraction: adding  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
V[14:16:00.326] System include extraction: adding  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include
V[14:16:00.326] System include extraction: adding  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include
V[14:16:00.326] System include extraction: adding  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
V[14:16:00.326] System include extraction: adding  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks (framework directory)
I[14:16:00.326] System include extractor: successfully executed /usr/bin/clang++, got includes: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1, /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include, /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include, /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include, /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks (framework directory)"
I[14:16:00.326] ASTWorker building file /Users/rdacs/Desktop/Project/qtMetal/main.mm version 1 with command 
[/Users/rdacs/Desktop/Project/qtMetal/build]
/usr/bin/clang++ --driver-mode=g++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/Users/rdacs/Desktop/Project/qtMetal/build/qt_and_metal_autogen/include -I/Users/rdacs/Desktop/Project/qtMetal/src -I/Users/rdacs/Desktop/Project/qtMetal/hellotriangle -iframework /Users/Shared/Qt/5.15.1/clang_64/lib -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtCore.framework/Headers -isystem /Users/Shared/Qt/5.15.1/clang_64/./mkspecs/macx-clang -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtWidgets.framework/Headers -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -fmodules -fcxx-modules -fPIC -std=gnu++11 -o CMakeFiles/qt_and_metal.dir/main.mm.o -c /Users/rdacs/Desktop/Project/qtMetal/main.mm -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks (framework directory) -fsyntax-only -resource-dir=/Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
V[14:16:00.328] Driver produced command: cc1 -cc1 -triple x86_64-apple-macosx10.15.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.mm -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-rounding-math -munwind-tables -target-sdk-version=11.1 -fcompatibility-qualified-id-block-type-checking -target-cpu penryn -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -target-linker-version 609 -resource-dir /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0 -iframework /Users/Shared/Qt/5.15.1/clang_64/lib -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtCore.framework/Headers -isystem /Users/Shared/Qt/5.15.1/clang_64/./mkspecs/macx-clang -isystem /Users/Shared/Qt/5.15.1/clang_64/lib/QtWidgets.framework/Headers -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks (framework directory) -D QT_CORE_LIB -D QT_GUI_LIB -D QT_WIDGETS_LIB -I /Users/rdacs/Desktop/Project/qtMetal/build/qt_and_metal_autogen/include -I /Users/rdacs/Desktop/Project/qtMetal/src -I /Users/rdacs/Desktop/Project/qtMetal/hellotriangle -stdlib=libc++ -internal-isystem /usr/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/local/include -internal-isystem /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -std=gnu++11 -fdeprecated-macro -fdebug-compilation-dir /Users/rdacs/Desktop/Project/qtMetal/build -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmodules -fimplicit-module-maps -fmodules-cache-path=/var/folders/_9/9bbm5_j108q5y6r82ty2rd9m0000gn/C/clang/ModuleCache -fmodules-validate-system-headers -fobjc-runtime=macosx-10.15.0 -fobjc-exceptions -fcxx-exceptions -fexceptions -fmax-type-align=16 -x objective-c++ /Users/rdacs/Desktop/Project/qtMetal/main.mm
I[14:16:00.328] --> textDocument/clangd.fileStatus
V[14:16:00.328] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes,running Update (1)","uri":"file:///Users/rdacs/Desktop/Project/qtMetal/main.mm"}}

V[14:16:00.328] Building first preamble for /Users/rdacs/Desktop/Project/qtMetal/main.mm version 1
V[14:16:00.370] Dropped diagnostic: /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0/include/module.modulemap: redefinition of module '_Builtin_intrinsics'
V[14:16:00.370] Dropped diagnostic: /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0/include/module.modulemap: redefinition of module '_Builtin_stddef_max_align_t'
V[14:16:00.547] Dropped diagnostic: /Users/rdacs/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0/include/module.modulemap: redefinition of module 'opencl_c'
V[14:16:00.562] BackgroundIndex: building version 1 after loading index from disk
[Info  - 2:16:00 PM] Connection to server got closed. Server will restart.
[Error - 2:16:00 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 2:16:00 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 2:16:00 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at ClangdLanguageClient.handleConnectionClosed (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/Users/rdacs/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
```

**System information**
Output of `clangd --version`: 11.0.0
Editor/LSP plugin: VS Code Clangd plugin
Operating system: macOS 10.15.7

**Comment by sam-mccall** [comment]
Module imports won't work without -fmodules indeed. (Just -fcxx-modules isn't enough, that flag means basically "if -fmodules is passed, *also* use modules for c++" and it's on by default)

@gislan fixed some -fmodules crashes, I believe as part of the clangd 12 release cycle. Can you try https://github.com/clangd/clangd/releases/tag/12.0.0-rc1 ?

**Comment by drink-crow** [comment]
> Module imports won't work without -fmodules indeed. (Just -fcxx-modules isn't enough, that flag means basically "if -fmodules is passed, _also_ use modules for c++" and it's on by default)
> 
> @gislan fixed some -fmodules crashes, I believe as part of the clangd 12 release cycle. Can you try https://github.com/clangd/clangd/releases/tag/12.0.0-rc1 ?

I try `12.0.0-rc2`, It dont crash with again and @import XXX work. but there `12.0.0-rc2` bring another issue that    
```
In included file: could not build module 'std'clang(module_not_built)
```

I ensure that is OK in version 11.0.0
