### ISSUE TITLE
An erroneous warning

### ISSUE THREAD

**Issue by Feacur** [clangd/clangd#744]
... I'm not sure if that's due to a compiler/analizer bug or something else

The EasyClangComplete, which interfaces with `libclang`, shows the same exact behaviour (https://github.com/niosus/EasyClangComplete/issues/744)

# What happens:  #
An erroneous warning `no new line at end of file` at an indented line near a forward declaration.

Minimal example 1:
```
#include <stdio.h>

	// reports `no new line at end of file`; forward declaration is mandatory
static void func(void);
int main(int argc, char const * argv[]) {
	(void)argc; (void)argv;
	func();
	return 0;
}

static void func(void) {
	printf("hello, world!\n");
}
```

Minimal example 2:

```
#include <stdio.h>

	static void func(void); // reports `no new line at end of file`; forward declaration is mandatory
int main(int argc, char const * argv[]) {
	(void)argc; (void)argv;
	func();
	return 0;
}

static void func(void) {
	printf("hello, world!\n");
}
```

Implied flags:
```
-std=c99
-Werror
-Weverything
```

Reference settings: https://github.com/Feacur/game_prototype/tree/master/__sublime_project

<details>
<summary>Log (Language servers) that illustrates the issue: </summary>
  
```
:: --> clangd initialize(1): {'rootPath': 'F:\\Projects\\game_prototype\\prototype', 'rootUri': 'file:///F:/Projects/game_prototype/prototype', 'workspaceFolders': [{'name': 'prototype', 'uri': 'file:///F:/Projects/game_prototype/prototype'}, {'name': '__sublime_project', 'uri': 'file:///F:/Projects/game_prototype/__sublime_project'}, {'name': 'framework', 'uri': 'file:///F:/Projects/game_prototype/framework'}, {'name': 'application', 'uri': 'file:///F:/Projects/game_prototype/application'}, {'name': 'third_party', 'uri': 'file:///F:/Projects/game_prototype/third_party'}, {'name': 'assets', 'uri': 'file:///F:/Projects/game_prototype/assets'}, {'name': 'project', 'uri': 'file:///F:/Projects/game_prototype/project'}, {'name': 'bin', 'uri': 'file:///F:/Projects/game_prototype/bin'}, {'name': '__vscode_workspace', 'uri': 'file:///F:/Projects/game_prototype/__vscode_workspace'}], 'capabilities': {'experimental': {}, 'textDocument': {'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'dynamicRegistration': True, 'hierarchicalDocumentSymbolSupport': True}, 'completion': {'dynamicRegistration': True, 'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'references': {'dynamicRegistration': True}, 'synchronization': {'dynamicRegistration': True, 'willSaveWaitUntil': True, 'willSave': True, 'didSave': True}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'hover': {'dynamicRegistration': True, 'contentFormat': ['markdown', 'plaintext']}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}, 'formatting': {'dynamicRegistration': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'documentHighlight': {'dynamicRegistration': True}, 'publishDiagnostics': {'relatedInformation': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'codeAction': {'dynamicRegistration': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'colorProvider': {'dynamicRegistration': True}, 'rename': {'dynamicRegistration': True}}, 'window': {'workDoneProgress': True, 'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}}, 'workspace': {'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceFolders': True, 'workspaceEdit': {'documentChanges': True, 'failureHandling': 'abort'}, 'configuration': True, 'executeCommand': {}, 'applyEdit': True, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'dynamicRegistration': True}}}, 'processId': 16976, 'initializationOptions': {}, 'clientInfo': {'name': 'Sublime Text LSP', 'version': '0.14.3'}}
clangd: I[19:05:56.823] clangd version 11.0.0
clangd: I[19:05:56.824] PID: 26488
clangd: I[19:05:56.824] Working directory: F:\Projects\game_prototype\prototype
clangd: I[19:05:56.824] argv[0]: C:/Program Files/LLVM/bin/clangd.exe
clangd: I[19:05:56.824] argv[1]: --log=verbose
clangd: I[19:05:56.824] argv[2]: -compile-commands-dir=F:\Projects\game_prototype\__sublime_project
clangd: V[19:05:56.832] User config file is C:\Users\Feacu\AppData\Local\clangd\config.yaml
clangd: I[19:05:56.832] Starting LSP over stdin/stdout
clangd: V[19:05:56.832] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"experimental":{},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":[]}},"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"dynamicRegistration":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"publishDiagnostics":{"relatedInformation":true},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"executeCommand":{},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort"},"workspaceFolders":true}},"clientInfo":{"name":"Sublime Text LSP","version":"0.14.3"},"initializationOptions":{},"processId":16976,"rootPath":"F:\\Projects\\game_prototype\\prototype","rootUri":"file:///F:/Projects/game_prototype/prototype","workspaceFolders":[{"name":"prototype","uri":"file:///F:/Projects/game_prototype/prototype"},{"name":"__sublime_project","uri":"file:///F:/Projects/game_prototype/__sublime_project"},{"name":"framework","uri":"file:///F:/Projects/game_prototype/framework"},{"name":"application","uri":"file:///F:/Projects/game_prototype/application"},{"name":"third_party","uri":"file:///F:/Projects/game_prototype/third_party"},{"name":"assets","uri":"file:///F:/Projects/game_prototype/assets"},{"name":"project","uri":"file:///F:/Projects/game_prototype/project"},{"name":"bin","uri":"file:///F:/Projects/game_prototype/bin"},{"name":"__vscode_workspace","uri":"file:///F:/Projects/game_prototype/__vscode_workspace"}]}}
clangd: 
clangd: I[19:05:56.833] <-- initialize(1)
clangd: I[19:05:56.835] --> reply:initialize(1) 2 ms
clangd: V[19:05:56.835] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","member","function","member","variable","class","enum","enumConstant","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 11.0.0"}}}
clangd: 
clangd: V[19:05:56.842] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}
clangd: 
:: <<< clangd 1: {'serverInfo': {'name': 'clangd', 'version': 'clangd version 11.0.0'}, 'capabilities': {'codeActionProvider': {'codeActionKinds': ['quickfix', 'refactor', 'info']}, 'documentHighlightProvider': True, 'definitionProvider': True, 'typeHierarchyProvider': True, 'selectionRangeProvider': True, 'declarationProvider': True, 'completionProvider': {'allCommitCharacters': [' ', '\t', '(', ')', '[', ']', '{', '}', '<', '>', ':', ';', ',', '+', '-', '/', '*', '%', '^', '&', '#', '?', '.', '=', '"', "'", '|'], 'triggerCharacters': ['.', '<', '>', ':', '"', '/'], 'resolveProvider': False}, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'documentLinkProvider': {'resolveProvider': False}, 'referencesProvider': True, 'executeCommandProvider': {'commands': ['clangd.applyFix', 'clangd.applyTweak']}, 'documentRangeFormattingProvider': True, 'textDocumentSync': {'change': 2, 'openClose': True, 'save': True}, 'workspaceSymbolProvider': True, 'documentOnTypeFormattingProvider': {'firstTriggerCharacter': '\n', 'moreTriggerCharacter': []}, 'hoverProvider': True, 'documentSymbolProvider': True, 'semanticTokensProvider': {'legend': {'tokenTypes': ['variable', 'variable', 'parameter', 'function', 'member', 'function', 'member', 'variable', 'class', 'enum', 'enumConstant', 'type', 'dependent', 'dependent', 'namespace', 'typeParameter', 'concept', 'type', 'macro', 'comment'], 'tokenModifiers': []}, 'full': {'delta': True}, 'range': False}, 'renameProvider': True, 'documentFormattingProvider': True}}
clangd: I[19:05:56.842] <-- initialized
::  -> clangd initialized: {}
clangd: V[19:05:56.846] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"c","text":"#include <stdio.h>\n\n\t// reports `no new line at end of file`; forward declaration is mandatory\nstatic void func(void);\nint main(int argc, char const * argv[]) {\n\t(void)argc; (void)argv;\n\tfunc();\n\treturn 0;\n}\n\nstatic void func(void) {\n\tprintf(\"hello, world!\\n\");\n}\n","uri":"file:///F:/Projects/game_prototype/prototype/test.c","version":0}}}
clangd: 
clangd: I[19:05:56.846] <-- textDocument/didOpen
clangd: I[19:05:56.848] Loaded compilation database from F:\Projects\game_prototype\__sublime_project
clangd: I[19:05:56.848] --> window/workDoneProgress/create(0)
clangd: V[19:05:56.848] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}
::  -> clangd textDocument/didOpen
clangd: 
clangd: I[19:05:56.848] Enqueueing 0 commands for indexing
clangd: I[19:05:56.848] ASTWorker building file F:\Projects\game_prototype\prototype\test.c version 0 with command
:: <-- clangd window/workDoneProgress/create(0): {'token': 'backgroundIndexProgress'}
clangd: [F:\Projects\game_prototype\__sublime_project]
:: >>> clangd 0: None
clangd: C:\Program Files\LLVM\bin\clang-tool -std=c99 -Werror -Weverything -Wno-switch-enum -Wno-float-equal -Wno-reserved-id-macro -Wno-nonportable-system-include-path -Wno-assign-enum -Wno-bad-function-cast -I.. -I../third_party -DGAME_TARGET_DEBUG -D_CRT_SECURE_NO_WARNINGS -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DUNICODE F:\Projects\game_prototype\prototype\test.c -fsyntax-only -resource-dir=C:\Program Files\LLVM\lib\clang\11.0.0
:: <-  clangd $/progress: {'value': {'percentage': 0, 'title': 'indexing', 'kind': 'begin'}, 'token': 'backgroundIndexProgress'}
clangd: V[19:05:56.848] <<< {"id":0,"jsonrpc":"2.0","result":null}
:: <-  clangd $/progress: {'value': {'message': '0/1', 'percentage': 0, 'kind': 'report'}, 'token': 'backgroundIndexProgress'}
clangd: 
:: <-  clangd $/progress: {'value': {'message': '0/1', 'percentage': 0, 'kind': 'report'}, 'token': 'backgroundIndexProgress'}
clangd: I[19:05:56.849] <-- reply(0)
:: <-  clangd $/progress: {'value': {'kind': 'end'}, 'token': 'backgroundIndexProgress'}
clangd: I[19:05:56.849] --> $/progress
clangd: V[19:05:56.849] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}
clangd: 
clangd: I[19:05:56.849] --> $/progress
clangd: V[19:05:56.849] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}
clangd: 
clangd: I[19:05:56.849] --> $/progress
clangd: V[19:05:56.849] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}
clangd: 
clangd: I[19:05:56.850] --> $/progress
clangd: V[19:05:56.850] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"end"}}}
clangd: 
clangd: V[19:05:56.860] Driver produced command: cc1 -cc1 -triple x86_64-pc-windows-msvc19.28.29910 -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -resource-dir C:\Program Files\LLVM\lib\clang\11.0.0 -I .. -I ../third_party -D GAME_TARGET_DEBUG -D _CRT_SECURE_NO_WARNINGS -D WIN32_LEAN_AND_MEAN -D NOMINMAX -D UNICODE -internal-isystem C:\Program Files\LLVM\lib\clang\11.0.0\include -internal-isystem C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include -internal-isystem C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\atlmfc\include -internal-isystem C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -Werror -Weverything -Wno-switch-enum -Wno-float-equal -Wno-reserved-id-macro -Wno-nonportable-system-include-path -Wno-assign-enum -Wno-bad-function-cast -std=c99 -fdebug-compilation-dir F:\Projects\game_prototype\__sublime_project -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.28.29910 -fdelayed-template-parsing -faddrsig -x c F:\Projects\game_prototype\prototype\test.c
clangd: V[19:05:56.860] Building first preamble for F:\Projects\game_prototype\prototype\test.c version 0
clangd: V[19:05:56.941] indexed preamble AST for F:\Projects\game_prototype\prototype\test.c version 0:
clangd: symbol slab: 1654 symbols, 457584 bytes
clangd: ref slab: 0 symbols, 0 refs, 136 bytes
clangd: relations slab: 0 relations, 24 bytes
clangd: V[19:05:56.969] Build dynamic index for header symbols with estimated memory usage of 1264344 bytes
clangd: V[19:05:56.976] Built preamble of size 843252 for file F:\Projects\game_prototype\prototype\test.c version 0
clangd: V[19:05:56.998] indexed file AST for F:\Projects\game_prototype\prototype\test.c version 0:
:: <-  clangd textDocument/publishDiagnostics: {'uri': 'file:///F:/Projects/game_prototype/prototype/test.c', 'diagnostics': [{'severity': 1, 'relatedInformation': [], 'message': 'No newline at end of file (fix available)', 'range': {'end': {'character': 1, 'line': 2}, 'start': {'character': 1, 'line': 2}}, 'source': 'clang', 'code': '-Wnewline-eof'}], 'version': 0}
clangd: symbol slab: 2 symbols, 4688 bytes
clangd: ref slab: 1 symbols, 1 refs, 4256 bytes
clangd: relations slab: 0 relations, 24 bytes
clangd: V[19:05:56.998] Build dynamic index for main-file symbols with estimated memory usage of 12016 bytes
clangd: I[19:05:56.998] --> textDocument/publishDiagnostics
clangd: V[19:05:56.998] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"-Wnewline-eof","message":"No newline at end of file (fix available)","range":{"end":{"character":1,"line":2},"start":{"character":1,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}],"uri":"file:///F:/Projects/game_prototype/prototype/test.c","version":0}}
clangd: 
```

</details>

<details>
<summary>Log (Sublime Text 3) that illustrates the issue: </summary>
  
```
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["EasyClangComplete", "Vintage"]
pre session restore time: 0.156727
startup time: 0.253727
first paint time: 0.255727
git: tracking working dir F:\Projects\game_prototype
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.10-wcwidth
reloading plugin 0_package_control_loader.40-pywinpty
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-pyte
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BuildX.ansi
reloading plugin BuildX.buildx
reloading plugin BuildX.test-color-scheme
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Feacu\AppData\Roaming\Sublime Text 3\Installed Packages\BuildX.sublime-package\test-color-scheme.py", line 5
    print(f"\x1b[0m\x1b[{code}m{name}\x1b[0m")
                                            ^
SyntaxError: invalid syntax
reloading plugin HexViewer.hex_checksum
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin HLSL Syntax.Scripts
reloading plugin LSP.boot
recreating index
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin ProjectManager.json_file
reloading plugin ProjectManager.project_manager
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin Terminus.main
reloading plugin User.plugins
plugins loaded
```

</details>

**System information**
Output of `clangd --version`: clangd version 11.0.0
Editor/LSP plugin: Sublime Text 3 (Version 3.2.2, Build 3211) / https://packagecontrol.io/packages/LSP (1.2.13 / 0.14.3)
Operating system: Windows 10 Home, 10.0.19042 Build 19042

**Comment by Feacur** [comment]
Thank you!
